### ISSUE TITLE
Where's the GitHub Preview Tab?

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/TeamBlogFeedback#1]
When I'm creating issues on docs.microsoft.com does all of markdown goodness work?  After submitting another issue, I now see it does but it is not obvious.  Where's my preview tab that renders my markdown?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* [Content](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* [Content Source](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: unspecified

**Comment by spottedmahn** [comment]
UserVoice feedback item created: [Add Preview Tab for GitHub Documentation Feedback](https://msdocs.uservoice.com/forums/364242-site-feedback/suggestions/33496399-add-preview-tab-for-github-documentation-feedback)

**Comment by dend** [comment]
Thanks @spottedmahn! Closing this issue as it is product feedback.
