### ISSUE TITLE
I owe you a beer!

### ISSUE THREAD

**Issue by Pernickety-Jon** [MicrosoftDocs/TeamBlogFeedback#104]
Hello. I found your page "Troubleshooting Disk Management" and, referred from that, "Change a Drive Letter".  They have solved weeks of annoyances and a day of headache. Thank you very much. If I could buy you a beer, or coffee, or... whatever, I would. The solution was so simple and staring me in the face but, after fruitless searching and trying other solutions, it was right click and add a drive letter.
Great work you good people of ... Microsoft (or elsewhere?). You've made my day! I had to join GitHub to leave this comment but you deserve it.
Best wishes,
Jon (Pernickety-Jon)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
We'll let @lizap know about the outstanding beverage offer! 👏 Thank you for the kudos!
