### ISSUE TITLE
Media Session Playback Example

### ISSUE THREAD

**Issue by beru** [MicrosoftDocs/TeamBlogFeedback#107]
Sample source files are broken and no archive file is provided.
https://docs.microsoft.com/en-us/windows/desktop/medfound/media-session-playback-example

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-ca/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
@beru can you please provide more context as to what is wrong? Links seem to work OK.

**Comment by beru** [comment]
@dend I can't download an archive file from the example page.
So I had to manually copy & paste each of the sample files. Surprisingly, all the `&` letters were displayed as `&amp;`, so I needed to replace them.

It seems the website has been updated and it has `Copy` button next so source file header, so things are getting better.

**Comment by dend** [comment]
Got it, thanks for the feedback! @ginami to help address.

**Comment by ginami** [comment]
Hi @beru -- thanks for your feedback. We will investigate!

**Comment by mlottner** [comment]
Closing this issue as resolved. If further action is required, please re-open and let us know. 
Appreciate your contribution to our community!
