### ISSUE TITLE
Awesome...but samples need to 'just work'

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/TeamBlogFeedback#109]
Great idea, awesome. Really like that you've included the ability to control the API version and HTTP request headers also.

The first thing I tried was to create a virtual network (https://docs.microsoft.com/rest/api/virtualnetwork/virtualnetworks/createorupdate). The first sample on that page didn't work, error 'locationRequired'. Easy fix, but It would be good if EVERY sample JUST WORKED. I should be able to copy+paste any of the samples into this new REST API tool, and run them successfully without modification. (From a MS point of view, it should be easy to automate/monitor testing that the samples work so you can maintain a high bar...)

Thanks again for the great feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8833410e-2016-3687-4ff0-296652bb6d87
* Version Independent ID: f6a120df-bfab-a876-2c0d-a84e8710f7ef
* Content: [Announcing Updates to the REST API Experience](https://docs.microsoft.com/en-us/teamblog/announcing-rest-improvements)
* Content Source: [teamblog/announcing-rest-improvements.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/announcing-rest-improvements.md)
* Product: **team-blog**
* GitHub Login: @hellosnow
* Microsoft Alias: **jehuan**

**Comment by hellosnow** [comment]
@jtuliani thank you for trying the try-it in REST API pages.

I checked the content on https://docs.microsoft.com/zh-cn/rest/api/virtualnetwork/virtualnetworks/createorupdate#request-body, that "location" is not required, could you copy paste your response in try-it section so that I could pass the information to Azure network team? Thanks. 😄

**Comment by jtuliani** [comment]
HTTP 400 with response body:
{
  "error": {
    "code": "LocationRequired",
    "message": "The location property is required for this definition."
  }
}

Note that 'location' is a required property across all resource types. This specific issue goes much further than just Networking. The general principle I'm proposing is that all samples should work, and you're going to have to look at them to work out which are broken in a generic way and which have resource-type-specific issues.

**Comment by priyankashb** [comment]
Thanks @jtuliani

Same error was coming on my webpage https://rrbgroupdresults2019.in/ while creating the app. but now all problem solved..

Thanks again everyone :)

**Comment by mlottner** [comment]
Closing this issue. If required, feel free to re-open and respond.
