### ISSUE TITLE
🐛 BUG: Markdown Syntax Issue

### ISSUE THREAD

**Issue by ahmadawais** [MicrosoftDocs/TeamBlogFeedback#112]
Folks 👋
There's a markdown syntax issue with a missing `)` for the job `[Cloud Ops Advocate | USA Mountain View](https://careers.microsoft.com/us/en/job/454630/Cloud-Ops-Advocate`. 

I hope it helps.
Peace! ✌️

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94615642-7eb7-83dd-52f1-ef6b78c687cf
* Version Independent ID: 69e13745-a61d-9309-96b8-c102d01a70ec
* Content: [Join our team and make the world better for developers!](https://docs.microsoft.com/en-us/teamblog/awesome-jobs?WT.mc_id=jobs-twitter-jeffsand#feedback)
* Content Source: [teamblog/awesome-jobs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/awesome-jobs.md)
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by dend** [comment]
Should be fixed now, thanks for the feedback @ahmadawais!

**Comment by ahmadawais** [comment]
@dend it is. Glad to help. Peace! ✌️
