### ISSUE TITLE
Upboard squared

### ISSUE THREAD

**Issue by emanueleleoni** [MicrosoftDocs/TeamBlogFeedback#113]
Hi, 
I would like to install iot core by dashboard, bit this device is not available now.
Do you know if It Will be in the list?
And when?

Waiting for your reply.
Best regards,
Emanuele

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/it-it/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by spottedmahn** [comment]
Hi @emanueleleoni - this issue doesn't seem related to the new feedback system.

**Comment by dend** [comment]
I am closing this issue as it is not related to the blog post at hand. That said, feel free to comment on the article for the service with which you are encountering issues, or go to https://azure.microsoft.com/en-us/support/options/.
