### ISSUE TITLE
When routing from content pages shall be available?

### ISSUE THREAD

**Issue by GITAhmad123** [MicrosoftDocs/TeamBlogFeedback#115]
Its long since content pages don’t have option to post the comments. Any updates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by EisenbergEffect** [comment]
@jdanyow It would be cool if my name didn't appear on these and I didn't keep getting email (since I don't work for Microsoft).

**Comment by jdanyow** [comment]
@EisenbergEffect I'll take your login/alias out of this article's metadata.

**Comment by dend** [comment]
Merging this change to live, @jdanyow @EisenbergEffect

**Comment by EisenbergEffect** [comment]
Much thanks @dend and @jdanyow ! Keep up the great work. I'm never to far away :)

**Comment by GITAhmad123** [comment]
@dend 
Thanks for your feedback, but please if i need to confirm about following team

https://docs.microsoft.com/en-us/sql/t-sql/functions/floor-transact-sql?view=sql-server-2017

?
They are still noticing to "Soon"; and i am unable to add feedback there....!!

Your help shall be appreciated.

Thanks
