### ISSUE TITLE
Turn on GitHub Issues for Microsoft-Supplied ODBC Drivers

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/TeamBlogFeedback#117]
Any chance GitHub issues can get turned on for: [Microsoft-Supplied ODBC Drivers](https://docs.microsoft.com/en-us/sql/odbc/microsoft/microsoft-supplied-odbc-drivers?view=sql-server-2017)?  Thanks 🙏

cc: @craigg-msft @iRaindrop @CarlRabeler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by craigg-msft** [comment]
@spottedmahn thank you for the question.  We are investigating switching that entire repo from Livefyre to git issues.  We are working to verify we have everything lined up in terms of workflow and participation as there is a lot of content in that repo and we want to find the proper balance between helping customers and not turning the content site into a tech support site which it is not designed for and we are not staffed for. Would you mind telling me the type of things you would leverage the  issues feature for?

**Comment by spottedmahn** [comment]
>We are investigating switching that entire repo from Livefyre to git issues.

👍👍

>Would you mind telling me the type of things you would leverage the issues feature for?

It's intended purpose, documentation issues 😊

**Comment by spottedmahn** [comment]
Today I was looking to provide feedback here: [Add Database Reference Dialog Box](https://docs.microsoft.com/en-us/sql/ssdt/add-database-reference-dialog-box?view=sql-server-2017)

That is under the "same" project, right?

**Comment by anakrantau12** [comment]
Whats the project is?

Pada tanggal 7 Sep 2018 22:04, "Michael DePouw" <notifications@github.com>
menulis:

**Comment by spottedmahn** [comment]
https://docs.microsoft.com/en-us/sql/ssdt/add-database-reference-dialog-box?view=sql-server-2017

and

https://docs.microsoft.com/en-us/sql/odbc/microsoft/microsoft-supplied-odbc-drivers?view=sql-server-2017

Are those under the same project?  If GitHub issues are turned on [for the original request](https://docs.microsoft.com/en-us/sql/odbc/microsoft/microsoft-supplied-odbc-drivers?view=sql-server-2017), would it turn it on [for SSDT too](https://docs.microsoft.com/en-us/sql/odbc/microsoft/microsoft-supplied-odbc-drivers?view=sql-server-2017)?

**Comment by craigg-msft** [comment]
@spottedmahn apologies for the delay.  we did turn on issues but for a limited number of folders so we can control the volume some.  we are not resourced if there was feedback on all the topics and clearly we are already behind  / losing track now and then :) For the sql-docs-pr repo we have issues enabled for the newer tech for now.  while the issues control is on only for some folders of topics, you could also create an issue in the repo itself https://github.com/MicrosoftDocs/sql-docs/issues.

**Comment by spottedmahn** [comment]
Fair enough, thanks @craigg-msft 😊
