### ISSUE TITLE
Beware of quotes in the 'name' elements

### ISSUE THREAD

**Issue by kuhlaid** [MicrosoftDocs/TeamBlogFeedback#119]
If you place quotes around the 'name' elements in a record (in this case, 'Flavor' and 'Quantity' you will receive an error (probably 'expecting indent' or 'expecting colon')
```
// the following example will not work
Collect( IceCream, { "Flavor": "Pistachio", "Quantity": 40 })

// leaving off the quotes on the 'name' element is acceptable, however you must keep them on the 'value' element (such as 'Pistachio')
Collect( IceCream, { Flavor: "Pistachio", Quantity: 40 })
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by mlottner** [comment]
@kuhlaid Thanks again for taking the time to give us feedback!
I'm closing this issue as we haven't heard back from you. 
If you still need help or have additional site feedback, feel free to re-open as needed.
