### ISSUE TITLE
No fulltext search for the writing style guide?

### ISSUE THREAD

**Issue by DieterGust** [MicrosoftDocs/TeamBlogFeedback#121]
I'd like to search the style guide for certain terms. I don't recognize a full-text search option. The search button on top searches all of Microsoft.
For me the full-text search is the by far the most important feature. Do I miss something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 590ef2fd-0b1a-a2e0-d6a5-109f997f1db7
* Version Independent ID: 913df696-e028-f6b4-2a41-f203798badb0
* Content: [Microsoft Writing Style Guide Released](https://docs.microsoft.com/en-us/teamblog/style-guide#feedback)
* Content Source: [teamblog/style-guide.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/style-guide.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **danielfe**

**Comment by dend** [comment]
Hello! The writing style guide now has a search scope, that should limit the search exclusively to the guide:

![image](https://user-images.githubusercontent.com/1389609/46051063-3d6a6d80-c0ec-11e8-9f52-8e88cf7a8c4e.png)
