### ISSUE TITLE
Dead UserVoice link

### ISSUE THREAD

**Issue by ite-klass** [MicrosoftDocs/TeamBlogFeedback#123]
The feedback link to UserVoice is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15ad50e0-d41c-b337-bc30-740efa744058
* Version Independent ID: cb9b9aa8-390b-8c97-1049-22aa1708b66a
* Content: [Announcing a unified .NET reference experience on docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/announcing-unified-dotnet-experience-on-docs)
* Content Source: [teamblog/announcing-unified-dotnet-experience-on-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/announcing-unified-dotnet-experience-on-docs.md)
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by dend** [comment]
Hi @ite-klass - at the time when the blog post was written, the UserVoice service was used for docs feedback. This has since changed to GitHub.

**Comment by ite-klass** [comment]
While that explains dead links it does not validate them or means that they make sense.
