### ISSUE TITLE
Versioning Information

### ISSUE THREAD

**Issue by OwlInSunglasses** [MicrosoftDocs/TeamBlogFeedback#124]
Sorely missing is the version of PowerShell (or programming language) that supports the modules/commands being described. E.g. Resolve-DnsName - under the h1 tag for Resolve-DnsName is a metadata div that denotes Resolve-DnsName is provided by the DnsClient module; but there is no indication that both require 2012 Server or equivalent version of PowerShell. As such, Windows 7 users are left mystified as to why that command will not run on their workstations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by mlottner** [comment]
@OwlInSunglasses Thanks for taking the time to give us blog feedback. 
In the future, make sure to open Git feedback on the page you have comments for. Direct page feedback ensure the right product owners have immediate access to our comments and requests. 
In the meantime, I've forwarded your comments. 
Appreciate your contribution to our community.
