### ISSUE TITLE
Spelling Mistake in Powershell Command 

### ISSUE THREAD

**Issue by kvs1983** [MicrosoftDocs/TeamBlogFeedback#125]
In the article https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/cluster-log-always-on-availability-groups?view=sql-server-2017, importing powershell module has spelling mistake. It was wrongly typed as **Import-Modeul** instead of **Import-Module**.
Correction is required in the powershell command.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca2544b-ea59-50ea-d831-cd4cc1778326
* Version Independent ID: 710c2742-9297-bb9d-d7ec-3a3bd269e8c4
* Content: [CLUSTER.LOG (Always On Availability Groups)](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/cluster-log-always-on-availability-groups?view=sql-server-2017)
* Content Source: [cluster-log-always-on-availability-groups.md](https://github.com/MicrosoftDocs/sql-docs-pr/blob/live/docs/database-engine/availability-groups/windows/cluster-log-always-on-availability-groups.md)
* Product: **SQL**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by dend** [comment]
There is a PR with the change:
https://github.com/MicrosoftDocs/sql-docs/pull/1003

Thank you for the feedback, @kvs1983!

**Comment by mlottner** [comment]
@kvs1983 Thanks again for your feedback. 
I'm closing this issue, feel free to re-open if/as needed.
