### ISSUE TITLE
Well done!!

### ISSUE THREAD

**Issue by systemeintegratedsolutions** [MicrosoftDocs/TeamBlogFeedback#126]
Well done! I've always loathed and avoided the MS documentation as much as possible, but it's getting better and better! I've ofte seen comments in documentation that were never replied to and I was a little disappointed, but this new system should go a LONG way to help with that. Well done guys!! You guys are working tirelessly to make the lives of developers easier and you deserve some credit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by dend** [comment]
Thank you for the kudos! 👏
