### ISSUE TITLE
Microsoft .NET APIs

### ISSUE THREAD

**Issue by amarinfotech** [MicrosoftDocs/TeamBlogFeedback#128]
Thank you for your information. Now we able to get all api information on same place..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 874a937b-9533-5d3b-bea7-722649cf4b5e
* Version Independent ID: c026ede2-0b6b-9d06-b31d-4030cb45a596
* Content: [.NET API Documentation Moved from MSDN to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/dotnet-api-docs-migration)
* Content Source: [teamblog/dotnet-api-docs-migration.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/dotnet-api-docs-migration.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by dend** [comment]
Thank you for the feedback! 👏
