### ISSUE TITLE
Can I ask help here about WinHttp websocket api?

### ISSUE THREAD

**Issue by ehaerim** [MicrosoftDocs/TeamBlogFeedback#129]
I see a good sample showing [Asynchronous Completion in WinHTTP](https://msdn.microsoft.com/en-us/library/aa383138%28VS.85%29.aspx#callback).
Unforturnately this sample is quite an old one that seems to be written before WinHttp supports WinHttpWebsocketSend / WinHttpWebSocketReceive.

I would like ask help to modify the above Asynchronous Completion in WinHttp **using WinHttpWebSocketSend/WinHttpWebSocketReceive in asynchronous mode**.

For example, there is a websocket server site : **wss://api.upbit.com/websocket/v1**
Once connecte, send the following sample string to the server : **[{"ticket":"test"},{"type":"ticker","codes":["KRW-BTC"]}]**
Then the following response will be received :
**{"market":"KRW-BTC","opening_price":8450000.00000000,"high_price":8679000.00000000,"low_price":8445000.00000000,"trade_price":8629000.0,"prev_closing_price":8450000.00000000,"acc_trade_price":105514711074.18726000,"change":"RISE","change_price":179000.00000000,"signed_change_price":179000.00000000,"change_rate":0.0211834320,"signed_change_rate":0.0211834320,"ask_bid":"ASK","trade_volume":0.0105675,"acc_trade_volume":12312.36058857,"trade_date":"20180418","trade_time":"100729","trade_timestamp":1524046049000,"acc_ask_volume":5703.42273172,"acc_bid_volume":6608.93785685,"highest_52_week_price":28885000.00000000,"highest_52_week_date":"2018-01-06","lowest_52_week_price":3286000.00000000,"lowest_52_week_date":"2017-09-15","trade_status":"ACTIVE","market_state":"ACTIVE","market_state_for_ios":"ACTIVE","is_trading_suspended":false,"delisting_date":null,"market_warning":"NONE","timestamp":1524046049766,"acc_trade_price_24h":55330325803.78210000,"acc_trade_volume_24h":6448.96200341}
 {"market":"KRW-BTC","opening_price":8450000.00000000,"high_price":8679000.00000000,"low_price":8445000.00000000,"trade_price":8629000.0,"prev_closing_price":8450000.00000000,"acc_trade_price":105515441503.850220000,"change":"RISE","change_price":179000.00000000,"signed_change_price":179000.00000000,"change_rate":0.0211834320,"signed_change_rate":0.0211834320,"ask_bid":"ASK","trade_volume":0.08464824,"acc_trade_volume":12312.44523681,"trade_date":"20180418","trade_time":"100730","trade_timestamp":1524046050000,"acc_ask_volume":5703.50737996,"acc_bid_volume":6608.93785685,"highest_52_week_price":28885000.00000000,"highest_52_week_date":"2018-01-06","lowest_52_week_price":3286000.00000000,"lowest_52_week_date":"2017-09-15","trade_status":"ACTIVE","market_state":"ACTIVE","market_state_for_ios":"ACTIVE","is_trading_suspended":false,"delisting_date":null,"market_warning":"NONE","timestamp":1524046050758,"acc_trade_price_24h":55330325803.78210000,"acc_trade_volume_24h":6448.96200341}**
...

**Comment by dend** [comment]
@ehaerim is there an article on docs.microsoft.com where this sample is referenced?

**Comment by mlottner** [comment]
@ehaerim Thanks again for taking the time to give us feedback. 
I'm closing this issue as we haven't heard back from you. 
Feel free to re-open if/as needed.
