### ISSUE TITLE
It's still hard to distinguish between product and documentation bugs sometimes

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/TeamBlogFeedback#132]
... apologies for opening issues in the wrong place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs?hubRefSrc=email&utm_source=lfemail&utm_medium=email#lf-content=229122660:775519037&reply_editor=true)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by dend** [comment]
@StingyJack not a problem - for content bugs, make sure to comment on the article itself. For site feedback, please refer to https://aka.ms/sitefeedback. For product feedback, teams will typically include a link within their own documentation that points to the right place.

**Comment by StingyJack** [comment]
As long as it's ok that I continue to report issues in the wrong place when unsure, or report them as documentation issues if I can't find the product link easily (SQL server or a Windows tool like pwrcfg.exe).
