### ISSUE TITLE
Remove mention of sidenotes

### ISSUE THREAD

**Issue by jffriend** [MicrosoftDocs/TeamBlogFeedback#133]
Since it appears the functionality has been removed it would be good to remove the mention of sidenotes from the blog post.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079073a-0dd9-3b9b-c160-76e0dd525a3c
* Version Independent ID: 631788a5-f4bc-7df0-0540-2a0f67b631de
* Content: [Introducing docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/introducing-docs-microsoft-com#feedback)
* Content Source: [teamblog/introducing-docs-microsoft-com.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-docs-microsoft-com.md)
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by mlottner** [comment]
@jffriend Thanks for your blog feedback. 
I'll work to get the sidenotes mention removed from the post.
