### ISSUE TITLE
reuse microsoft.com docs platform for customer api ref docs

### ISSUE THREAD

**Issue by guybartal** [MicrosoftDocs/TeamBlogFeedback#134]
does the Microsoft.com docs platform OSS?
my customer would like to reuse this platform + feedback feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by AlexHedley** [comment]
I raised [73](https://github.com/MicrosoftDocs/TeamBlogFeedback/issues/73) 6 months ago, I’m hoping the API Help you can add to WebAPI projects can use the new Try It feature for our own APIs too

**Comment by mlottner** [comment]
@guybartal Thanks for your question!
The Microsoft Docs platform was custom built and continues to be internally maintained on top of GitHub. Base functionality is of course available from GitHub including the ability to add issues such as these to a repo. The possibilities for docs platforms on GitHub are nearly endless, but  docs.microsoft.com is not open source. In addition, the page Feedback feature is provided by a third party. 
Appreciate your contribution to our docs community.
