### ISSUE TITLE
Outdated link to UserVoice

### ISSUE THREAD

**Issue by gix** [MicrosoftDocs/TeamBlogFeedback#135]
The feedback section links to a discontinued UserVoice instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a2e7010-ba7b-ead7-ebf0-b91f2289738e
* Version Independent ID: 22e6a5ce-3f3f-0c65-eb84-17eea02f0d43
* Content: [New and Updated Offline Books](https://docs.microsoft.com/en-us/teamblog/offline-book-refresh-feb-2018)
* Content Source: [teamblog/offline-book-refresh-feb-2018.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/offline-book-refresh-feb-2018.md)
* Product: **team-blog**
* GitHub Login: @mikeblome
* Microsoft Alias: **mikeblome**

**Comment by mlottner** [comment]
@gix Thanks for your feedback. 
Unfortunately, as we switch delivery systems, links to old features and support systems are occasionally not maintained. I'll try to see if the post can be updated and fixed. For site feedback, you can always use the link at the bottom of any docs.microsoft.com page. 
Appreciate your contribution to our community.
