### ISSUE TITLE
The link to Github  is broken

### ISSUE THREAD

**Issue by sulmar** [MicrosoftDocs/TeamBlogFeedback#136]
The link to Github (https://github.com/microsoftgraph/microsoft-graph-doc) is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc610a58-f74a-d759-5e12-885d1eb9169e
* Version Independent ID: 5f119970-6ee2-33cd-ba47-7c5531738b48
* Content: [Microsoft Graph documentation now on docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/graph-on-docs?wt.mc_id=docsmsft-twitter)
* Content Source: [teamblog/graph-on-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/graph-on-docs.md)
* Product: **team-blog**
* GitHub Login: @thedanfernandez
* Microsoft Alias: **danielfe**

**Comment by nschonni** [comment]
It's missing an "s" on the end. Should be https://github.com/microsoftgraph/microsoft-graph-docs

**Comment by mlottner** [comment]
@sulmar Thanks for taking the type to report this issue. 
I've edited the page and submitted a pull request to fix the link.
