### ISSUE TITLE
All well and good but please share the code with us mere mortals!

### ISSUE THREAD

**Issue by TotallyInformation** [MicrosoftDocs/TeamBlogFeedback#137]
This is great and works really well, but how are you sharing this ability with the rest of the world?

In particular, why not add some GitHub and Markdown love to SharePoint Online document libraries to make it easy to use Office 365 for creating and managing documentation as code?

Don't keep it to yourself :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by mlottner** [comment]
@TotallyInformation Thanks for taking the time to give us your feedback. 
I've flagged the relevant teams to make them aware of your feature request. Unfortunately, docs.microsoft.com infrastructure is not currently an open source project or one that is a shippable product, but we certainly appreciate the acknowledgement of all of the teams involved in bringing the site to life and maintaining it!
