### ISSUE TITLE
Offline Availability

### ISSUE THREAD

**Issue by Emmanuel-GD** [MicrosoftDocs/TeamBlogFeedback#139]
I am using this documentation and it is very helpful but what about making it available in visual studio offline book? So that anyone offline will have access to it from help viewer.
Thank You.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a2e7010-ba7b-ead7-ebf0-b91f2289738e
* Version Independent ID: 22e6a5ce-3f3f-0c65-eb84-17eea02f0d43
* Content: [New and Updated Offline Books](https://docs.microsoft.com/en-us/teamblog/offline-book-refresh-feb-2018)
* Content Source: [teamblog/offline-book-refresh-feb-2018.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/offline-book-refresh-feb-2018.md)
* Product: **team-blog**
* GitHub Login: @mikeblome
* Microsoft Alias: **mikeblome**

**Comment by mlottner** [comment]
@Emmanuel-GD Thanks for taking the time to leave us your feedback. 
docs.microsoft.com is comprised of thousands of pages of content and is updated multiple times of day from thousands of contributors around the globe. Making an offline (and updated/accurate) version would be virtually impossible and constantly inaccurate.
Appreciate your contribution to our community.
