### ISSUE TITLE
Broken Docs search (Desktop/Win32 API)

### ISSUE THREAD

**Issue by changov** [MicrosoftDocs/TeamBlogFeedback#142]
I did a basic search for a Win32 API constant: https://docs.microsoft.com/en-us/search/index?search=WS_EX_APPWINDOW&scope=Desktop . All the hits on the first page were random junk. Whereas Bing's first result is the right reference page: https://www.bing.com/search?q=WS_EX_APPWINDOW&PC=U316&FORM=CHROMN . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by mlottner** [comment]
@changov Thanks for taking the time to give us feedback. 
Search on Docs continues to be upgraded and enhanced, with more improvements planned in the coming months.
