### ISSUE TITLE
cannot hide sidebar

### ISSUE THREAD

**Issue by lukacs-andras** [MicrosoftDocs/TeamBlogFeedback#143]
The sidebar of the old docs site can be collapsed but not on the new site. This may not be a problem if you view the site in landscape mode because the text is wide enough. However, if you set up your monitor in portrait mode so you can see more text on a single screen, the useful text may be too narrow. The sidebar should be collapsable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 874a937b-9533-5d3b-bea7-722649cf4b5e
* Version Independent ID: c026ede2-0b6b-9d06-b31d-4030cb45a596
* Content: [.NET API Documentation Moved from MSDN to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/dotnet-api-docs-migration)
* Content Source: [teamblog/dotnet-api-docs-migration.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/dotnet-api-docs-migration.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by mlottner** [comment]
@lukacs-andras Thanks for taking the time to give us site usability feedback. 
I've flagged this request to our usability team for further investigation. I'm closing the issue, but feel free to re-open if/as needed with further feedback.  
Appreciate your contribution to our community.
