### ISSUE TITLE
Is there a template for this style of website we can use?

### ISSUE THREAD

**Issue by christopher-brock** [MicrosoftDocs/TeamBlogFeedback#146]
In order to provide better feedback it would be great if we could use a template for the website to create our own internal documentation site, then once we fully test and find the best way to utilise it, we can provide better feedback.

Is this something that is available?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1ebe2f1-9d33-1460-76fe-709b2c0f5702
* Version Independent ID: 149b0cc9-2cc2-9ca2-e78f-01f5dcaeb8ea
* Content: [Help shape the future of docs.microsoft.com!](https://docs.microsoft.com/en-us/teamblog/user-study-announcement-november-2017#feedback)
* Content Source: [teamblog/user-study-announcement-november-2017.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/user-study-announcement-november-2017.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dend**

**Comment by mlottner** [comment]
@christopher-brock Thanks so much for taking the time to leave us feedback. 
Unfortunately, docs.microsoft.com is not currently available as an accessible external template. 
It takes a large team within Microsoft to build and maintain it 24/7 and isn't yet an external facing offering.
