### ISSUE TITLE
Layout source code for docs.microsoft.com website 

### ISSUE THREAD

**Issue by tb-mtg** [MicrosoftDocs/TeamBlogFeedback#147]
In the spirit of now being open-source i was hoping somebody could share the code and any third-party css & js libraries that may have been used for the template/layout page for the docs.microsoft.com website.  

I love the design and am especially interested in the following work:

* the Left sidebar "Contents" menu and it's ability to filter even with sub-navigation menus
* the Right sidebar "In this article" menu
* the Breadcrumbs across the top

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b82e6d10-f967-0026-c23c-c1c19fecde7b
* Version Independent ID: 4fd67d8e-096b-9207-0542-4b8a3bb63a66
* Content: [Release Notes - January 2019](https://docs.microsoft.com/en-us/teamblog/release-notes-january-2019)
* Content Source: [teamblog/release-notes-january-2019.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/release-notes-january-2019.md)
* Product: **team-blog**
* GitHub Login: @dendeli-msft
* Microsoft Alias: **dendeli-msft**

**Comment by mlottner** [comment]
@tb-mtg Thanks for taking the time to give us feedback and throw some love at docs!
Unfortunately, docs.microsoft.com isn't currently a publicly available template or layout. It takes a large team at Microsoft to continuously write, maintain and build the site 24/7, but we do appreciate your recognition of our efforts. I have alerted the site infrastructure team of your request. 

Appreciate your contribution to our community.
