### ISSUE TITLE
Estimated Reading Time calculation

### ISSUE THREAD

**Issue by brikken** [MicrosoftDocs/TeamBlogFeedback#149]
How do you calculate the Estimated Reading Time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079073a-0dd9-3b9b-c160-76e0dd525a3c
* Version Independent ID: 631788a5-f4bc-7df0-0540-2a0f67b631de
* Content: [Introducing docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/introducing-docs-microsoft-com)
* Content Source: [teamblog/introducing-docs-microsoft-com.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-docs-microsoft-com.md)
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by mlottner** [comment]
@brikken Thanks for your question!
Our estimated reading calculation is 200 words per minute. All pages with 400 or fewer words are estimated at 2 minutes.
