### ISSUE TITLE
This is a Lol

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/TeamBlogFeedback#15]
Hello Lols

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com | Microsoft Docs](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by gregdegruy** [comment]
Seriously though. How can I branch and give direct doc feedback now? https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/clientapi/reference/xrm-navigation/openalertdialog The feedback button just brings me to the comment section. I can always go directly to GitHub I suppose. https://github.com/MicrosoftDocs/dynamics-365-customer-engagement-pr

**Comment by dend** [comment]
@gregdegruy teams are still transitioning to the GitHub model so it might take a bit for it to be enabled everywhere. In the meantime, going directly to the repo and contacting the team through that channel is the best way to do it.
