### ISSUE TITLE
When will other people be able to embed Github Issues into their own documentation solutions?

### ISSUE THREAD

**Issue by sb2059** [MicrosoftDocs/TeamBlogFeedback#150]
I'd love to be able to leverage this capability on my own projects.  Are there plans to share this functionality?  If so, what does the timeline look like?  We need to decide whether or not to roll our own.  Thanks and great work, Rob and co!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs#feedback)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by shirgoldbird** [comment]
One of our excellent engineers, @jdanyow, has made an open-source version of the commenting system. You can find it [here](https://github.com/utterance/utterances).

Glad you like it!
