### ISSUE TITLE
What's the feedback issue limit per user, per repository, per day?

### ISSUE THREAD

**Issue by Player1UK** [MicrosoftDocs/TeamBlogFeedback#151]
I've currently got 164 open issues in 1 repository, which I created over the space of roughly 3 days, after signing up to Github as a new user to leave feedback.
And now all I see is "Loading feedback..." for all pages within that documentation repository.
Is there a limit to the amount of feedback one user can give?  Is there a limit period for new users?  Have I been locked out of this repository?  And is there a way of checking for this status?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs#your-feedback)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by mlottner** [comment]
@Player1UK Thanks for taking the time to leave your question on blog feedback. 
I'm unaware of any limit on issues in a repository and regularly work on repositories with hundreds of issues with no loading issues. 
Has this issue continued? I'm closing this issue for now, but feel free to re-open it if/as you continue to require assistance on this.

**Comment by Player1UK** [comment]
Whatever I did must have resulted in an issue being identified something being fixed, as over a short period back in June the issue gradually got resolved.
My feedback cadence has since declined, however, after finishing submitting all the fixes I had.

**Comment by mlottner** [comment]
@Player1UK Glad to hear it is fixed. 
Appreciate your contribution to our docs community!
