### ISSUE TITLE
Feedback functionality missing

### ISSUE THREAD

**Issue by TobiasKnauss** [MicrosoftDocs/TeamBlogFeedback#153]
Where has the feedback functionality gone on all the pages that contain the .net command reference? Like https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlnode.selectsinglenode
I would like to point to errors on this page, but I can't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs#feedback)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by mlottner** [comment]
@TobiasKnauss Thanks for taking the time to give us your feedback. 
I've tagged this issue for the .NET experience team to investigate. 
In the meantime, you can submit issues using the **edit** option at the top of each page. Submit your fix by editing the page and submitting a PR for faster resolution.

**Comment by stmax82** [comment]
@mlottner the feedback functionality still hasn't returned to the API docs.. what happened to it and is there a new way to report bugs in the documentation?

**Comment by mlottner** [comment]
@stmax82 Until the feedback functionality returns to the page, your best method is to open a PR on the page as I suggested previously. Otherwise, flag the page you would like to comment on with a new site feedback issue and we'll flag it for fix with the .NET team.

**Comment by mimisasouvanh** [comment]
The feedback control was moved to the upper right corner of the page. You'll see "Is this page helpful"
![image](https://user-images.githubusercontent.com/7453668/74290682-6f7f6e00-4ce7-11ea-9a6a-2f32c44f45d1.png)

**Comment by mlottner** [comment]
@mimisasouvanh I believe both @stmax82 and @TobiasKnauss were looking for the page "feedback" mechanism where they can report content bugs, and ask for clarifications. Not the actual feedback button of voting whether or not the page is helpful. While the feedback button opens a dialog box, it may not be clear that it can be used for requesting corrections etc. as other pages on docs.microsoft.com display, and does not offer issue tracking etc. I think that was the intent of these comments.

**Comment by stmax82** [comment]
Yes I meant the feedback functionality that creates issues on github.. best thing ever added to Microsoft docs:

![image](https://user-images.githubusercontent.com/6381927/74412293-5e487580-4e3d-11ea-91c2-315cbf18c1d1.png)

I'm not clicking the "Is this page helpful?" button because you never know if anyone's ever going to look at and use this data.

Not really happy about the "Edit" button either.. when I click the edit button on the [GZipStream](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.gzipstream?view=netcore-3.1) page, I get a ton of xml that I wouldn't dare touching because I don't know its format and there's no preview:

![image](https://user-images.githubusercontent.com/6381927/74412752-6b199900-4e3e-11ea-94aa-78e5997c18dc.png)

**Comment by TobiasKnauss** [comment]
> @mimisasouvanh I believe both @stmax82 and @TobiasKnauss were looking for the page "feedback" mechanism where they can report content bugs, and ask for clarifications. Not the actual feedback button of voting whether or not the page is helpful. While the feedback button opens a dialog box, it may not be clear that it can be used for requesting corrections etc. as other pages on docs.microsoft.com display, and does not offer issue tracking etc. I think that was the intent of these comments.

Exactly.

@stmax82: I agree, I wouldn't edit ans content either, especially since this is not my job. MS should be glad that we're already telling them when we find faulty or unclear parts on their documentation. If they remove that feedback mechanism, this looks like they don't want our qualified feedback any more and instead ignore us users again, as it has been their practice for years.
