### ISSUE TITLE
Windows Server 2016 and Windows 10 IT pro docs are now on docs.microsoft.com

### ISSUE THREAD

**Issue by caeschlimann** [MicrosoftDocs/TeamBlogFeedback#154]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1e30a04-2564-d7c1-1d40-676decb4645c
* Version Independent ID: 612d3858-e4f6-d775-7ea5-3c77a89752f7
* Content: [Windows Server 2016 and Windows 10 IT pro docs are now on docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/windows-server-and-10-it-docs)
* Content Source: [teamblog/windows-server-and-10-it-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/windows-server-and-10-it-docs.md)
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by mlottner** [comment]
@caeschlimann Thanks for getting in touch. 
Your feedback is blank, so I'm unsure how we can help. 
I'm closing this issue, but feel free to re-open if /as you require additional assistance.
