### ISSUE TITLE
Docs userVoice link not avaliable

### ISSUE THREAD

**Issue by wenmin92** [MicrosoftDocs/TeamBlogFeedback#155]
The last paragraph contains a the Docs UserVoice link which 404.
https://msdocs.uservoice.com/forums/364242-general-site-feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe0825e-ebb0-7d41-7225-74098be2f9fa
* Version Independent ID: 33b86421-2f7d-8401-4ed9-a616952feea2
* Content: [Updates to our PowerShell Documentation Experience](https://docs.microsoft.com/en-us/teamblog/updated-powershell-experience)
* Content Source: [teamblog/updated-powershell-experience.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/updated-powershell-experience.md)
* Product: **team-blog**
* GitHub Login: @thedanfernandez
* Microsoft Alias: **jeffsand**

**Comment by docs-product** [comment]
The link is no longer active - we rely on https://aka.ms/sitefeedback.
