### ISSUE TITLE
User created Category 

### ISSUE THREAD

**Issue by LivefromRaleighwood** [MicrosoftDocs/TeamBlogFeedback#156]
It looks like all the Bookmarks are dumped in to a single non-named Category or bucket. Most people would have a number of reasons....on different topics...to visit this site. As such, please add the ability to add topics or categories -- to allow us to put a bookmark IN a location we can easily reference....but we make them. Please allow the bookmarks to be dumped into OneNote. Please allow for a Memo Field to be attached to each bookmark. Please expose the Memo Field in a way that allows for it to be searched. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b42fca82-5d23-bc98-7c78-01b4da0abf54
* Version Independent ID: 2be86a04-0247-0d5f-50ce-967634838ba4
* Content: [Announcing Bookmarks for docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/announcing-bookmarks?WT.mc_id=docsmsft-twitter#feedback)
* Content Source: [teamblog/announcing-bookmarks.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/announcing-bookmarks.md)
* Product: **team-blog**
* GitHub Login: @charmaine
* Microsoft Alias: **dendeli**

**Comment by mlottner** [comment]
@LivefromRaleighwood 
Thanks for taking the time to give us feedback. 
I've flagged your bookmark features requests to our site experience team. 
Appreciate your contribution to our community!
