### ISSUE TITLE
TechNet Gallery also affected?

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/TeamBlogFeedback#157]
I dont seem to get the "sunsetting" banner on any of my code samples for the TechNet Gallery, but since they're practically the same platform, I figured I'd ask here. Does the above affect code samples submitted to the TechNet Gallery? If so, can you please make it clearer and also make sure to add the bar and any other type of warning. Also, can you please be more specific as to timelines on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09436f0c-bb2a-1729-cba8-b000b9888e2a
* Version Independent ID: a86eddce-6fc1-648a-9dc0-b634689b400a
* Content: [MSDN Code Gallery Retirement](https://docs.microsoft.com/en-us/teamblog/announcing-msdn-code-gallery-retirement)
* Content Source: [teamblog/announcing-msdn-code-gallery-retirement.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/announcing-msdn-code-gallery-retirement.md)
* Product: **team-blog**
* GitHub Login: @aprilspeight
* Microsoft Alias: **apspeigh**

**Comment by aprilspeight** [comment]
The banner that you are referring to is only for the MSDN Code Gallery and therefore will only display on MSDN Code Gallery pages. The MSDN Code Gallery will retire this month (November).

Additional information regarding the TechNet Gallery will be provided at a late date.

**Comment by michevnew** [comment]
Sorry to bring this up again, but currently the TechNet Gallery is in a very broken state:

![image](https://user-images.githubusercontent.com/38553333/74763684-e937ce80-5288-11ea-8f0c-5b8aa25a4d0e.png)

Is it still supported, I havent seen any announcements about retirement yet? Can you share the plans around this, and possibly find someone to fix the current issues?

**Comment by aprilspeight** [comment]
@rloutlaw could you please take a look into this issue? thanks!

**Comment by mlottner** [comment]
@docs-product Can you take a look this please and reassign as needed? Thanks!
