### ISSUE TITLE
Q&A vs. Tech Community?

### ISSUE THREAD

**Issue by jasontenpenny** [MicrosoftDocs/TeamBlogFeedback#158]
Can you elaborate a little on how you see this differing from the Microsoft Tech Community?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be114f3-6668-8b9d-b698-a088050edd1e
* Version Independent ID: 360c7943-63c3-72b8-ddbe-b275f86793ba
* Content: [Introducing Microsoft Q&A (Preview)](https://docs.microsoft.com/en-us/teamblog/introducing-microsoft-qanda#feedback)
* Content Source: [teamblog/introducing-microsoft-qanda.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-microsoft-qanda.md)
* Product: **team-blog**
* GitHub Login: @saldana
* Microsoft Alias: **saldana**

**Comment by MohitGargMSFT** [comment]
Microsoft Q&A will use the same user authentication as Microsoft Docs and Learn content for a more consistent experience across the platform. This integrated experience will allow us to better prioritize and answer questions, and give users clearer paths between documentation, learning content, and answers. Microsoft Q&A also offers a much better set of permissions that will equip our moderators with improved tools.
Reference: https://docs.microsoft.com/answers/articles/388/microsoft-qa-frequently-asked-questions.html

**Comment by jasontenpenny** [comment]
yeah I guess I was more wondering what kind of content y'all are expecting to be posted in one vs the other. They both seem like they're accomplishing more or less the same thing. That's why I was looking for clarification.

**Comment by saldana** [comment]
@jasontenpenny  The current scope is to move customers from MSDN and TechNet forums to Microsoft Q&A. Other platforms will co-exist, and we will look at ways to consolidate and share content between the different sites. So if you are collaborating in MSDN Forums for the services we are onboarding, then we are inviting you to do so in Microsoft Q&A. If you are engaging in Tech Community, you should continue doing so.
