### ISSUE TITLE
Microsoft Answers?

### ISSUE THREAD

**Issue by bgiesing** [MicrosoftDocs/TeamBlogFeedback#159]
Will this also replace Microsoft Answers too or just MSDN/TechNet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be114f3-6668-8b9d-b698-a088050edd1e
* Version Independent ID: 360c7943-63c3-72b8-ddbe-b275f86793ba
* Content: [Introducing Microsoft Q&A (Preview)](https://docs.microsoft.com/en-us/teamblog/introducing-microsoft-qanda#feedback)
* Content Source: [teamblog/introducing-microsoft-qanda.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-microsoft-qanda.md)
* Product: **team-blog**
* GitHub Login: @saldana
* Microsoft Alias: **saldana**

**Comment by saldana** [comment]
@bgiesing The current scope is to move customers from MSDN and TechNet forums to Microsoft Q&A. the scope for Answers remains as-is today. We will look at ways to consolidate and share content between the different sites.
