### ISSUE TITLE
Glad to see you're testing the new feedback buttons here.

### ISSUE THREAD

**Issue by tomresing** [MicrosoftDocs/TeamBlogFeedback#16]
This release notes article is the first time I've seen the new "Give documentation feedback" button work this well. I like how it allows adding the feedback to GitHub without leaving the page and it shows on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e493b93-e2f1-f396-9e87-d62dc93fbd04
* Version Independent ID: a32343b9-b3d8-32be-4a27-c57bb0a20453
* Content: [Starting 2018 With docs.microsoft.com Improvements | Microsoft Docs](https://docs.microsoft.com/en-us/teamblog/release-notes-start-2018)
* Content Source: [teamblog/release-notes-start-2018.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/release-notes-start-2018.md)
* Service: **unspecified**
* GitHub Login: @dend
* Microsoft Alias: **danielfe**

**Comment by mlottner** [comment]
@tomresing Thanks for taking the time to give us feedback!
Glad to see the new feedback functionality is working for you. 
I'm closing this issue for now, but feel free to re-open if/as needed.
