### ISSUE TITLE
Helpful to show example of marking an answer

### ISSUE THREAD

**Issue by wsmelton** [MicrosoftDocs/TeamBlogFeedback#160]
In order to better support and encourage questions to be marked as answer by those that ask it would be helpful to show how just an answer to the example question being marked as such.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be114f3-6668-8b9d-b698-a088050edd1e
* Version Independent ID: 360c7943-63c3-72b8-ddbe-b275f86793ba
* Content: [Introducing Microsoft Q&A (Preview)](https://docs.microsoft.com/en-us/teamblog/introducing-microsoft-qanda#feedback)
* Content Source: [teamblog/introducing-microsoft-qanda.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-microsoft-qanda.md)
* Product: **team-blog**
* GitHub Login: @saldana
* Microsoft Alias: **saldana**

**Comment by saldana** [comment]
@wsmelton this is a great suggestion and in the next few weeks we will work on providing some user scenario guidelines. Thanks!!!

Note that you can also add suggestions like this in the [Site feedback section in Microsoft Q&A](https://docs.microsoft.com/answers/content/idea/list.html)!
