### ISSUE TITLE
Cognitive Services, AI + Machine Learning

### ISSUE THREAD

**Issue by 217Wilder-User1** [MicrosoftDocs/TeamBlogFeedback#161]
https://docs.microsoft.com/answers/index.html looks really good.  Tons of potential.   Are there plans to incorporate Azure Cognitive Services or any Azure AI + Machine Learning services to the site?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be114f3-6668-8b9d-b698-a088050edd1e
* Version Independent ID: 360c7943-63c3-72b8-ddbe-b275f86793ba
* Content: [Introducing Microsoft Q&A (Preview)](https://docs.microsoft.com/en-us/teamblog/introducing-microsoft-qanda)
* Content Source: [teamblog/introducing-microsoft-qanda.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-microsoft-qanda.md)
* Product: **team-blog**
* GitHub Login: @saldana
* Microsoft Alias: **saldana**

**Comment by saldana** [comment]
Hi @217Wilder-User1 thanks a lot for the feedback. We are currently testing everything out with the subset of scenarios to make sure that the platform evolves to accommodate all the products and services. We are working very closely with the Azure team on an onboarding plan for all the Azure services into Q&A. We are doing the same for non-Azure products and services.

We do not have a date yet though. We will provide more updates in new blog posts as we have them. 

Thank you!!!
