### ISSUE TITLE
Q&A profile settings nit

### ISSUE THREAD

**Issue by frank-e** [MicrosoftDocs/TeamBlogFeedback#163]
Out of curiosity I tested the "sign in" (create account) procedure, actually I should have a working MS social/answers/technet/onedrive/life/whatever profile with the same e-mail address, but apparently this "docs"/"qanda" thingy is different (and on github):  Uploading a profile picture worked. Skipping the "e-mail + region" form worked. Disabling Q&A e-mails failed. Trying it again after adding the "e-mail + region" info also failed. Delete account worked, I really do not want unsolicited e-mail. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be114f3-6668-8b9d-b698-a088050edd1e
* Version Independent ID: 360c7943-63c3-72b8-ddbe-b275f86793ba
* Content: [Introducing Microsoft Q&A (Preview)](https://docs.microsoft.com/en-us/teamblog/introducing-microsoft-qanda#feedback)
* Content Source: [teamblog/introducing-microsoft-qanda.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-microsoft-qanda.md)
* Product: **team-blog**
* GitHub Login: @saldana
* Microsoft Alias: **saldana**

**Comment by mlottner** [comment]
@frank-e 
Thanks for taking the time to give us Docs site feedback!
To make sure we understand your issue I've attempted to condense it here: You don't want to have a separate alias for GitHub and want to use your existing Microsoft related alias and your want to be able to opt out of receiving additional emails related to GitHub. 
Is this accurate?

**Comment by frank-e** [comment]
I got lost in the e-mail settings, the account (github or MS) doesn't matter, it's anyway the same image and the same gmail address everywhere, but I rarely check my e-mail (roughly annually).

**Comment by mlottner** [comment]
@frank-e Thanks for answering. 
I've flagged your frustration with the email settings to our site design team for awareness and potential future adjustment. 
Appreciate your contribution to our user community!
