### ISSUE TITLE
In Docs/My profile/ Activity - Contraditory information

### ISSUE THREAD

**Issue by Pedrolorenzo** [MicrosoftDocs/TeamBlogFeedback#164]
In the section Activities or "Pick up where you left off", I have some modules listed, but I have finnished all of them.
It has contraditory information:

example:  

Publish and share in Power BI

 0% completed • 0 min remaining

Thank you

![activity](https://user-images.githubusercontent.com/57567101/69433167-df4e1000-0d19-11ea-9ee1-832874942cb7.PNG)

**Comment by mlottner** [comment]
@Pedrolorenzo Thanks for taking the time to give us feedback. 
I've tagged this issue for a member of our Learn infrastructure team to investigate for you. 
Appreciate your contribution to our community.
