### ISSUE TITLE
Hide the Left Navigation Pane

### ISSUE THREAD

**Issue by hugohhk** [MicrosoftDocs/TeamBlogFeedback#165]
Is it possible to implement a feature to hide the left navigation pane? 
The left navigation pane is taking up to much space on the page, and making the lines in paragraph too short. 
That makes the article as a whole very long and difficult to read. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079073a-0dd9-3b9b-c160-76e0dd525a3c
* Version Independent ID: 631788a5-f4bc-7df0-0540-2a0f67b631de
* Content: [Introducing docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/introducing-docs-microsoft-com#feedback)
* Content Source: [teamblog/introducing-docs-microsoft-com.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-docs-microsoft-com.md)
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by mlottner** [comment]
@hugohhk Thanks for taking the time to give us feedback. 
I've flagged this issue to the site improvement and enhancement team for awareness and possible inclusion in a future build. 
Appreciate your contribution to our community.
