### ISSUE TITLE
Track Teams Progress

### ISSUE THREAD

**Issue by marcelwicke** [MicrosoftDocs/TeamBlogFeedback#167]
Hi,
how is it possible to track progress of my team members I shared a collection with? Or is this an upcoming feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46c2a70c-c859-cccf-25c3-e2fd81216fc6
* Version Independent ID: 46eab899-7f9e-88a9-947a-2afba61ec984
* Content: [Announcing Learn Collections](https://docs.microsoft.com/en-us/teamblog/announcing-learn-collections?source=docs#feedback)
* Content Source: [teamblog/announcing-learn-collections.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/announcing-learn-collections.md)
* Product: **team-blog**
* GitHub Login: @jialge
* Microsoft Alias: **jialge**

**Comment by mlottner** [comment]
@marcelwicke Thanks so much for taking the time to ask your question and give us your feedback. 
At present, this feature is not available, but is being considered on the roadmap. 
I've flagged your request with a member of the relevant product teams for review and consideration. 
Appreciate your contribution to our customer community!
