### ISSUE TITLE
Can you allow creation of nested collection to release a single URL containing multiple learning path

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/TeamBlogFeedback#168]
It would be nice to have a collection made up of other collection (of learning path) and release it as a Cloud Skill Challenge with single URL for entire organization. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26c7d914-e786-d705-977d-4f5fe050f420
* Version Independent ID: 90e0d126-c3ff-00ec-b910-528c64a8c9db
* Content: [Introducing Microsoft.com/Learn](https://docs.microsoft.com/en-us/teamblog/introducing-ms-learn#feedback)
* Content Source: [teamblog/introducing-ms-learn.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-ms-learn.md)
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by mlottner** [comment]
@Anand-Moghe Thanks so much for taking the time to leave us your feedback and suggestion for Microsoft Learn. 

I've flagged your suggestion for internal review and consideration. 

We really appreciate your contribution to our customer community!

**Comment by Anand-Moghe** [comment]
@mlottner I have also noticed that I am unable to edit/Update the CSC with the TPID and Org Unit etc if it is of the type Collection. This need to be fixed as well. We need to allow CSC of Collection types to have those attribute as well so it is easier to track based on targets.

**Comment by mlottner** [comment]
@Anand-Moghe Thanks for this additional feedback. In the future, make sure to open a new feedback item if your ask or issue is different from the original issue. This ensures it always gets added to the feature request queue. Appreciate your contribution!

@yunyunyunyun Learn feature request list addition.
