### ISSUE TITLE
Full-screen immersion

### ISSUE THREAD

**Issue by AlexA-1976** [MicrosoftDocs/TeamBlogFeedback#169]
Is there a way have an article in 'readability mode' so that everything is hidden by the content?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079073a-0dd9-3b9b-c160-76e0dd525a3c
* Version Independent ID: 631788a5-f4bc-7df0-0540-2a0f67b631de
* Content: [Introducing docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/introducing-docs-microsoft-com#feedback)
* Content Source: [teamblog/introducing-docs-microsoft-com.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-docs-microsoft-com.md)
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by mlottner** [comment]
@AlexA-1976 Thanks for taking the time to give us your feedback and ask about new display features. At present, there isn't a way to hide all navigation and only display content on the platform. 
In the meantime, I've tagged your request to a member of the relevant team for review and consideration. We really appreciate your contribution to our user community!
