### ISSUE TITLE
You should archive IT Pro oriented code

### ISSUE THREAD

**Issue by otter007** [MicrosoftDocs/TeamBlogFeedback#175]
You should archive the itpro oriented code from the TechNet gallery.  Its still a good resource. You have made the developer oriented code available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12b90746-323d-e43e-6dd4-97859717447e
* Version Independent ID: 5d68ad61-ec5a-b909-a8a9-65d5d2feb61e
* Content: [TechNet Gallery Retirement](https://docs.microsoft.com/en-us/teamblog/technet-gallery-retirement)
* Content Source: [teamblog/technet-gallery-retirement.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/technet-gallery-retirement.md)
* Product: **team-blog**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by otter007** [comment]
As you suggested we can probably find this type of code on github or in blogs.  It will just take additional steps.  No need to spend time here.

**Comment by Abdul8383** [comment]
TechNet Gallery Retirement
Hi, I have lots of articles on TechNet gallery, are you going to migrate them all or do I have to take backup myself?
