### ISSUE TITLE
Influencer Program Strategy Lead - Broken

### ISSUE THREAD

**Issue by JuanKRuiz** [MicrosoftDocs/TeamBlogFeedback#18]
This URL is broken:: *Influencer Program Strategy Lead (1109064) new*
https://careers.microsoft.com/JobDetails.aspx?ss=&pg=0&so=&rw=1&jid=349503&jlang=EN&pp=SS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94615642-7eb7-83dd-52f1-ef6b78c687cf
* Version Independent ID: 69e13745-a61d-9309-96b8-c102d01a70ec
* Content: [Join our team and make the world better for developers! | Microsoft Docs](https://docs.microsoft.com/en-us/teamblog/awesome-jobs?WT.mc_id=jobs-twitter-jeffsand)
* Content Source: [teamblog/awesome-jobs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/awesome-jobs.md)
* Service: **unspecified**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by dend** [comment]
Thanks for the feedback @JuanKRuiz - the article has been updated.
