### ISSUE TITLE
Unable to send email apply for Moderator

### ISSUE THREAD

**Issue by cheong00** [MicrosoftDocs/TeamBlogFeedback#192]
In the blog entry it invites us Moderators/Answerers to mail to msdn-tn-2qamod AT microsoft.com to apply for Moderator role at Microsoft Q&A forum. However I'm unable to do so because of the following:

[quote]
The group msdn-tn-2qamod only accepts messages from people on its allowed senders list, and your email address isn't on the list.
[/quote]

May want to check the mailbox settings, or add some other ways of application.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7680b3-fdc6-3024-3220-3be443534828
* Version Independent ID: 20f4af54-8b63-c71c-3e19-4d0c043f432a
* Content: [MSDN and TechNet forum moderators to Microsoft Q&A](https://docs.microsoft.com/en-us/teamblog/qna-thank-you-msdn-technet-moderators)
* Content Source: [teamblog/qna-thank-you-msdn-technet-moderators.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/qna-thank-you-msdn-technet-moderators.md)
* Product: **team-blog**
* GitHub Login: @saldana

**Comment by saldana** [comment]
We fixed this last week. It was due to how I setup the distribution list and my lack of testing as I was heading towards vacation.
