### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/TeamBlogFeedback#193]
Sending email to msdn-tn-2qamod@microsoft.com renders;
  
"The group msdn-tn-2qamod only accepts messages from people on its allowed senders list, and your email address isn't on the list" 
   
Please remove the restriction on this address or change the page to another address without the restriction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7680b3-fdc6-3024-3220-3be443534828
* Version Independent ID: 20f4af54-8b63-c71c-3e19-4d0c043f432a
* Content: [MSDN and TechNet forum moderators to Microsoft Q&A](https://docs.microsoft.com/en-us/teamblog/qna-thank-you-msdn-technet-moderators)
* Content Source: [teamblog/qna-thank-you-msdn-technet-moderators.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/qna-thank-you-msdn-technet-moderators.md)
* Product: **team-blog**
* GitHub Login: @saldana

**Comment by saldana** [comment]
This was fixed last week. It was due to an issue with the configuration of the distribution list and my lack of testing as I was heading to vacation.

**Comment by DSPatrick** [comment]
Yea, just trying all avenues. Finally got Nandha to look and fix it or found someone that could.
