### ISSUE TITLE
this panel does not honor the back button properly

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/TeamBlogFeedback#23]
if i click a link and navigate elsewhere, going back does not show this section as it was

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
Hi @StingyJack - what section are you referring to?

**Comment by StingyJack** [comment]
The one where I entered the issue at on the docs page/blog post. (also that "content source" link above is a 404)
![image](https://user-images.githubusercontent.com/15381181/37572460-b9b500a4-2ae1-11e8-8468-504eeb765272.png)

**Comment by actionaer** [comment]
in my case, it looks perfect as it is. Exept i switched to Dark theme which is a need and handy too.

**Comment by StingyJack** [comment]
@actionaer - click on the closed list, then click on an issue in that list and be navigated to it. Now click back in the browser.  Unless it was fixed, it was returning to the Open list, not the Closed list.

**Comment by dend** [comment]
@ShevaDas as FYI on this ask.

**Comment by ShevaDas** [comment]
@StingyJack thanks for the feedback! I've filed an issue in our internal work tracker to resolve this and will follow up here when it's complete.

**Comment by mlottner** [comment]
@shirgoldbird Is there an update on this? I'd like to close if resolved or scheduled.

**Comment by docs-product** [comment]
@mlottner closing this issue as we do not have immediate plans on changing this behavior.
