### ISSUE TITLE
Improve the color contrast for the typing area in comments

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/TeamBlogFeedback#24]
where i need to type is the word Description, and looks like a caption (not greyed out, terse). Its nice you didnt just use a bottom border, but if you must follow this newish fad please use something like "type your description here" in grey.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
@ShevaDas can you help log this feedback item? It's in relation to the appearance of the comment box on docs.microsoft.com.

**Comment by StingyJack** [comment]
To be clear I was having trouble with this when using my mobile (android/chrome).  On the mobile, this Description box...
![image](https://user-images.githubusercontent.com/15381181/37572488-1525830a-2ae2-11e8-9f4f-bf3a2dc6811f.png)
... has borders that are very faint and the word **Description** as very bold and fills the text area. On desktop browser its not as stark of a contrast of faint and bold, and there is clear visible space around the word "Description". 

On both, however the text you intend to overtype should probably look like something to overtype and not like a caption or section header, and give a bit more than a one word instruction (that also lends itself to a caption).

The "new fad" ones I mentioned are the ones that have a single bottom border.

```
Name            <- page is expecting you to type here
--------------
                      <- but you are trying to type here 

Email
--------------
```

**Comment by actionaer** [comment]
What do you mean seriously?  If theres a field a Border and in that a transparent Word "Description" and thats perfect. If it would be a setence then it would look like you act. Keeping it simple.. and Windows anyways is full of words... than Linux for example

**Comment by StingyJack** [comment]
Its not transparent on mobile. Its full dark and the border is light enough to get lost depending on the screen brightness.  
![image](https://user-images.githubusercontent.com/15381181/37920003-9fb19402-30f3-11e8-940c-8e3300fceb27.png)

Its different (improved) than it was when I opened this issue, which was more like this...
![image](https://user-images.githubusercontent.com/15381181/37920182-2fc7914a-30f4-11e8-970c-f480ff84485d.png)
Based on that improvement, this could probably be closed, but the full dark text and border should really be swapped.

There is a difference between terse and so short it misleads users.

**Comment by dend** [comment]
+ @ShevaDas on this request.

**Comment by ShevaDas** [comment]
Hi @StingyJack, thanks for the feedback. Due to accessibility requirements, we can't change the placeholder text color to be a lighter shade of grey as that would cause problems for users with visual impairments. However, I have filed an issue in our internal work tracker to update the placeholder text to read "Leave a comment" (à la GitHub) and will follow up when it's updated.

**Comment by StingyJack** [comment]
@ShevaDas - That's fair, and I understand, Can you please reach out to the DevOps blog webmaster and get them to darken and enlarge the text in the comments box?

![image](https://user-images.githubusercontent.com/15381181/38306490-b5600efe-37de-11e8-81e4-badfc2827e80.png)
Example from https://blogs.msdn.microsoft.com/devops/2018/03/16/top-stories-from-the-vsts-community-2018-03-16/

**Comment by sharriexie** [comment]
@StingyJack , I'm PM of MSDN blog platform and could bring your feedback to DevOps webmaster. Just one question, is there any problem on current text and the comment box size? Given the background then  the webmater could properly triage this feedback.
Many thanks in advance.

**Comment by StingyJack** [comment]
@sharriexie - Here is another screencap that may help illustrate the difference. The text at the top in the bio is how the rest of the page looks, same font and color/weight, etc. 

Then there is the text at the bottom, faded and far too small.  The size of the box is gigantic looking compared to the text, but its the choice of font and its weight/color that is the problem.
![image](https://user-images.githubusercontent.com/15381181/38467202-e5385f06-3b02-11e8-97bb-8d7998f64a0e.png)

**Comment by ShevaDas** [comment]
@StingyJack To address your original feedback, we've updated the placeholder text for submitting new issues and comments to read "Leave a comment". This is now more consistent with the GitHub.com experience, and hopefully clearer to users. We appreciate the feedback and hope you enjoy the updates!

**Comment by sharriexie** [comment]
@StingyJack , DevOps team is making a plan to move their blog to a new platform and under redesign the new system. I'm still confirming with them to make sure you comment will be taken in the new design. Will that work for you?

**Comment by StingyJack** [comment]
Yeah, thats OK.   Just make sure some of the dev's that made the platform arent all eagle-eye'd 20 somethings. =P.
