### ISSUE TITLE
Roll-Out = mid-February ... why not rolled out mid-March ?

### ISSUE THREAD

**Issue by MarcioAB** [MicrosoftDocs/TeamBlogFeedback#25]
This post says the new feedback system will start to be rolled out in mid-Feb, but we are mid-March and I do not see much rolled out. What to expect about time ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
Hi @MarcioAB - we are in the process of rolling it out. It's already available for several large documentation sets.

**Comment by Baffour** [comment]
@dend Is there visibility of this anywhere, such as a status page? I keep wanting to reply to comments and then remembering they'll disappear imminently as the new feedback system replaces comment threads. 
If there is, could a link be added to this page under the roll out section?

**Comment by mlottner** [comment]
@MarcioAB Thanks for taking the time to share your feedback. 
I'm closing this issue as roll-out is complete. 
Feel free to re-open if/as you feel it is needed.
