### ISSUE TITLE
How to use IdentityServer3 or 4 in Azure B2c as custom policy

### ISSUE THREAD

**Issue by kamranbashir** [MicrosoftDocs/TeamBlogFeedback#26]
Sor far tried this, but did not work
<ClaimsProviders>
	<ClaimsProvider>
		<Domain>TCSL</Domain>
		<DisplayName>Login using TCSL</DisplayName>
		<TechnicalProfiles>
			<TechnicalProfile Id="ContosoProfile">
				<DisplayName>TCSL Employee</DisplayName>
				<Description>Login with your TCSL account</Description>
				<Protocol Name="OpenIdConnect"/>
				<OutputTokenFormat>JWT</OutputTokenFormat>
				<Metadata>
					<Item Key="METADATA">https://kamidp.azurewebsites.net/core/.well-known/openid-configuration</Item>
					<Item Key="ProviderName">TCSL</Item>
					<Item Key="authorization_endpoint">https://kamidp.azurewebsites.net/core/connect/authorize</Item>
					<Item Key="AccessTokenEndpoint">https://kamidp.azurewebsites.net/core/connect/token</Item>
					<Item Key="ClaimsEndpoint">https://kamidp.azurewebsites.net/core/connect/userinfo</Item>
					<Item Key="ClaimsEndpointAccessTokenName">id_token</Item>
					<Item Key="ClaimsEndpointFormatName">format</Item>
					<Item Key="ClaimsEndpointFormat">json</Item>
					<Item Key="scope">api1</Item>
					<Item Key="HttpBinding">POST</Item>
					<Item Key="UsePolicyInRedirectUri">0</Item>
					<Item Key="client_id">renukey</Item>
				</Metadata>	
				<CryptographicKeys>
				<Key Id="TcslExt" StorageReferenceId="B2C_1A_TcslExt"/>
				</CryptographicKeys>				
				<OutputClaims>
					<OutputClaim ClaimTypeReferenceId="socialIdpUserId" PartnerClaimType="oid"/>
					<OutputClaim ClaimTypeReferenceId="tenantId" PartnerClaimType="tid"/>
					<OutputClaim ClaimTypeReferenceId="givenName" PartnerClaimType="given_name" />
					<OutputClaim ClaimTypeReferenceId="surName" PartnerClaimType="family_name" />
					<OutputClaim ClaimTypeReferenceId="displayName" PartnerClaimType="name" />
					<OutputClaim ClaimTypeReferenceId="authenticationSource" DefaultValue="contosoAuthentication" />
					<OutputClaim ClaimTypeReferenceId="identityProvider" DefaultValue="AzureADContoso" />
				</OutputClaims>
				<OutputClaimsTransformations>
					<OutputClaimsTransformation ReferenceId="CreateRandomUPNUserName"/>
					<OutputClaimsTransformation ReferenceId="CreateUserPrincipalName"/>
					<OutputClaimsTransformation ReferenceId="CreateAlternativeSecurityId"/>
					<OutputClaimsTransformation ReferenceId="CreateSubjectClaimFromAlternativeSecurityId"/>
				</OutputClaimsTransformations>
				<UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop"/>
			</TechnicalProfile>
		</TechnicalProfiles>
	</ClaimsProvider> 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-gb/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
Hello! This looks like a product issue that you are encountering, and not directly connected to docs.microsoft.com - please make sure to use the correct team channel to make sure they see your feedback and can address it properly.
