### ISSUE TITLE
What about all the old comments?

### ISSUE THREAD

**Issue by andrewconnell** [MicrosoftDocs/TeamBlogFeedback#29]
*Don't get me wrong... I like this new model. *

But what about all the old comments on docs? There were a LOT of relevant comments there... are they lost?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
Hi @andrewconnell - the old comments will be archived. We are working with content developers to make sure that any relevant information from comments is always integrated back into the documentation.

**Comment by MTRuchi** [comment]
Can you please let me know by when we will be able to view old comments?
