### ISSUE TITLE
Links don't resolve to job descriptions

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/TeamBlogFeedback#30]
The links resolve to `https://careers.microsoft.com/`. It would be helpful if the position links resolved to job descriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94615642-7eb7-83dd-52f1-ef6b78c687cf
* Version Independent ID: 69e13745-a61d-9309-96b8-c102d01a70ec
* Content: [Join our team and make the world better for developers!](https://docs.microsoft.com/en-us/teamblog/awesome-jobs)
* Content Source: [teamblog/awesome-jobs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/awesome-jobs.md)
* Service: **unspecified**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by dend** [comment]
@marywill99 can you please verify the feedback from @guardrex?

**Comment by marywill99** [comment]
Thank you Den. The Careers site has totally changed so all of our tags are gone…urg... I’m going to fix tonight.

M

**Comment by janakar** [comment]
Also the Edit Profile section in the new careers site won't work. It says "Ooops an error has occurred". Can you redirect this to the relevant team?

**Comment by dend** [comment]
This has now been addressed!
