### ISSUE TITLE
cntk2.5 using keras

### ISSUE THREAD

**Issue by ywchiang0819121** [MicrosoftDocs/TeamBlogFeedback#35]
cntk2.5 using keras may cause python crash.
After I installed cntk and changed my keras backend to cntk, i tried to verified my keras work.
However, I import keras before it crash and it didn't list any error message.
Then, I downgrade cntk to 2.4 and it works.

All cntk above, using GPU version

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/zh-tw/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by mlottner** [comment]
@ywchiang0819121 Thanks for taking the time to give us site feedback. 
Make sure to leave product feedback or documentation questions on the specific page or product for which you have an issue. 
I'm closing this issue for now, as I don't know what specific docs page you meant to reference. Feel free to re-open if/as needed.
