### ISSUE TITLE
Onclick method for the children

### ISSUE THREAD

**Issue by marquessbr** [MicrosoftDocs/TeamBlogFeedback#38]
Hi!

How I can implement a OnClick method for all images assigned as a children of my wraplayout for when the user click in a image the OnClick make the image to be showed in the full screen?

thanks

**Comment by dend** [comment]
@marquessbr what product is your question related to?

**Comment by marquessbr** [comment]
the **ImageWrapLayout**, I need which they children have a onclick event for each one

**Comment by dend** [comment]
@marquessbr right, but what API/product are you using? This site is for blog feedback, so we don't triage product issues here. I'd like to make sure I point you in the right direction.

**Comment by marquessbr** [comment]
I dont is using any api, I got the example and try to implement it according my solution

**Comment by marquessbr** [comment]
Hi my friend!
I solved this, I just implement one GesturReconize for each image I get and it work fine here,
thank you, I'll close this issue now!
