### ISSUE TITLE
Best Docs Ever!

### ISSUE THREAD

**Issue by mirsaeedi** [MicrosoftDocs/TeamBlogFeedback#39]
Your novel approach to documentation is awesome and aspiring! I hope others learn from you that our today's complex world needs far better documentation for delivering high-quality codes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 699693b0-9b5d-f166-5519-13cc2908fa1d
* Version Independent ID: a0d3294f-1dbe-1fec-1f43-177a66811e30
* Content: [Release Notes - March 2018](https://docs.microsoft.com/en-us/teamblog/release-notes-march-2018)
* Content Source: [teamblog/release-notes-march-2018.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/release-notes-march-2018.md)
* Service: **unspecified**
* GitHub Login: @dend
* Microsoft Alias: **danielfe**

**Comment by dend** [comment]
Thanks for the feedback, @mirsaeedi!
