### ISSUE TITLE
SignalR JavaScript API

### ISSUE THREAD

**Issue by stamminator** [MicrosoftDocs/TeamBlogFeedback#40]
I love these API browsers! Are there plans to add the API documentation for the SignalR client to the new JavaScrip API browser? I think it will be especially necessary to have that when .NET Core 2.1 RTM is released because its jQuery dependency has been removed and there will likely be a lot of changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 699693b0-9b5d-f166-5519-13cc2908fa1d
* Version Independent ID: a0d3294f-1dbe-1fec-1f43-177a66811e30
* Content: [Release Notes - March 2018](https://docs.microsoft.com/en-us/teamblog/release-notes-march-2018)
* Content Source: [teamblog/release-notes-march-2018.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/release-notes-march-2018.md)
* Service: **unspecified**
* GitHub Login: @dend
* Microsoft Alias: **danielfe**

**Comment by dend** [comment]
Yes! We are currently working on onboarding those to docs.microsoft.com.

**Comment by mlottner** [comment]
@stamminator Thanks again for your question. 
I'm closing this issue as resolved. 
Please feel free to re-open if/as needed with additional blog feedback.
