### ISSUE TITLE
clean external network windows 10

### ISSUE THREAD

**Issue by mouadhbh1** [MicrosoftDocs/TeamBlogFeedback#41]
his a problem
think you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by EisenbergEffect** [comment]
@jdanyow Seems like there's a problem here. Note the GitHub Login and Microsoft Alias...

**Comment by EisenbergEffect** [comment]
@jdanyow Is this author notification of comments on articles?

**Comment by jdanyow** [comment]
This is a temporary concession to help the Azure CXP team triage issues while automation/webhook logic is being implemented. I can take your ms.author and author tags off the blog post(s) if you’d like.

**Comment by EisenbergEffect** [comment]
Makes sense. No need to remove my name unless it gets out of hand for some reason. I doubt there will be issues.

**Comment by dend** [comment]
@EisenbergEffect @jdanyow I will close this issue in the meantime 😄
