### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by EisenbergEffect** [MicrosoftDocs/TeamBlogFeedback#43]
Woohoo! Great to see this launching :) Congrats @meganbradley and @adkinn !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c101c482-1f4b-f4a9-9da1-91ad723c5bb5
* Version Independent ID: 8d19e1b7-1bd8-b556-d32a-8ddb1d14ea49
* Content: [Announcing the Docs Markdown Extension for Visual Studio Code](https://docs.microsoft.com/en-us/teamblog/docs-extension)
* Content Source: [teamblog/docs-extension.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/docs-extension.md)
* Service: **unspecified**
* GitHub Login: @adkinn
* Microsoft Alias: **adkinn**

**Comment by dend** [comment]
Thanks again for the kudos, @EisenbergEffect!
