### ISSUE TITLE
Migrating sql to Azure

### ISSUE THREAD

**Issue by dragonix11** [MicrosoftDocs/TeamBlogFeedback#48]
I'm curious about the scripts that support Azure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079073a-0dd9-3b9b-c160-76e0dd525a3c
* Version Independent ID: 631788a5-f4bc-7df0-0540-2a0f67b631de
* Content: [Introducing docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/introducing-docs-microsoft-com)
* Content Source: [teamblog/introducing-docs-microsoft-com.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-docs-microsoft-com.md)
* Service: **unspecified**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by dragonix11** [comment]
I am interested in the repository editor on windows pages, I am asking for comments

**Comment by mlottner** [comment]
@dragonix11 Thanks for taking the time to give us feedback on the new docs.microsoft.com!
Make sure to ask questions and post feedback on the specific product pages that can help you in your Azure journey to get fast response and guidance.
I'm closing this blog feedback issue, but feel free to re-open if/as you have additional feedback on our blogs.
