### ISSUE TITLE
MethodAccessException: Attempt by method  Microsoft.Azure.CosmosDB.Table.TableEntity.set_DisableCompiledSerializers(Boolean)

### ISSUE THREAD

**Issue by wpitallo** [MicrosoftDocs/TeamBlogFeedback#5]
Hi I am not sure where to get help with cosmos issues.

There seems to be an issue when trying to initilize an inherited Table

using Microsoft.Azure.CosmosDB.Table;
using Server.Base.Azure.Table.Adapters;
using Microsoft.Azure.Storage.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Server.Base.Azure.Table.Models
{
public class CosmosDbBase : TableEntity

{

    public string TableName { get; }
    public CloudTable Table { get; }

    public CosmosDbBase() --> Fails here: 
    {
        var i = 0;
    }
  }
}

I get the following error when trying to construct the class:

MethodAccessException: Attempt by method 'Microsoft.Azure.CosmosDB.Table.TableEntity.set_DisableCompiledSerializers(Boolean)' to access method 'Microsoft.Azure.Storage.Core.Util.PlatformAgnosticReflectionExtensions.FindStaticMethods(System.Type, System.String)' failed.

I can do the exact same thing with table storage and everything works perfectly, any ideas whats causing this?

System.TypeInitializationException
HResult=0x80131534
Message=The type initializer for 'Microsoft.Azure.CosmosDB.Table.TableEntity' threw an exception.
Source=Microsoft.Azure.CosmosDB.Table

Inner Exception 1:
MethodAccessException: Attempt by method 'Microsoft.Azure.CosmosDB.Table.TableEntity.set_DisableCompiledSerializers(Boolean)' to access method 'Microsoft.Azure.Storage.Core.Util.PlatformAgnosticReflectionExtensions.FindStaticMethods(System.Type, System.String)' failed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* [Content](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* [Content Source](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: unspecified

**Comment by mariuscotor** [comment]
just for testing: PSD - Ciuma rosie!

**Comment by dend** [comment]
Hello! This seems to be related to a product issue and not docs.microsoft.com. Please refer to [Cosmos DB](https://docs.microsoft.com/en-us/azure/cosmos-db/) documentation for more details.

**Comment by wpitallo** [comment]
Where exactly should I post this question, the support for CosmosDB is terrible. Can't find a proper place to ask a question...

**Comment by wpitallo** [comment]
Please can I have a proper address to ask a question and not just get re-directed back to the product page...
