### ISSUE TITLE
Documentation in different languages

### ISSUE THREAD

**Issue by jorgerodes** [MicrosoftDocs/TeamBlogFeedback#51]
Please do not let a machine make translations. Spanish translation of documentation is ilegible in most cases. Why dont you open a Translation proyect  where  we could collaborate voluntarily?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 38ef5be1-2def-575d-d803-c257bf1314f6
* Version Independent ID: 46f9065d-fa38-15ee-1200-8c16f5fce81a
* Content: [Help make docs.microsoft.com better!](https://docs.microsoft.com/es-es/teamblog/help-make-docs-microsoft-com-better)
* Content Source: [teamblog/help-make-docs-microsoft-com-better.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/help-make-docs-microsoft-com-better.md)
* Service: **unspecified**
* GitHub Login: @dend
* Microsoft Alias: **dend**

**Comment by perconey** [comment]
You can submit your own translations of the articles by clicking the edit button and making a pull request of your commit after signing the Microsoft Contributor License Agreement (CLA) available on https://opensource.microsoft.com/pdf/microsoft-contribution-license-agreement.pdf

**Comment by dend** [comment]
@SonjaSaltzman - can you please check-in here?

**Comment by SonjaSaltzman** [comment]
@jorgerodes - as pointed out by perconey, most of our content has the "Edit" button enabled, where you can directly edit the topics in your language on GitHub. 
We will also start enabling the feedback feature in coming weeks, so you can leave a comment and tell us what you are looking for.  If there is any specific topic you would like to see localized, please let us know.
