### ISSUE TITLE
Please Turn on for ASP.NET Core!

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/TeamBlogFeedback#53]
Love ❤ the new system here.  I've gotten use to it in Azure docs.

I'm always so disappointed when I go to [ASP.NET Core docs](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies) and it is not there.

When can we expect it?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
@danroth27 @Rick-Anderson - can you please help address this request?

**Comment by Rick-Anderson** [comment]
@dend  how do we enable it? We're ready. cc @mairaw @BillWagner

**Comment by MNF** [comment]
Please do not convert before archive of previous comments is implemented.

**Comment by dend** [comment]
@mairaw @Rick-Anderson - you can switch the feedback today. Comments will be archived within the next couple of months and will still be available in the backend.

**Comment by mairaw** [comment]
Ok. So folks who have commented won't be able to see their previous comments. If so, it would be good to clarify that in issue 17.

Do you know where we can find instructions to make the switch @dend?

**Comment by dend** [comment]
@mairaw - will share internally.

**Comment by MNF** [comment]
@mairaw, just want to clarify, that the problem is wider: no one will be able to access all comments, that were created during previous years until archive will be implemented.

**Comment by dend** [comment]
This has now been enabled for ASP.NET Core docs!

Please keep in mind that we are working on exporting LiveFyre comments, so those are not lost!
