### ISSUE TITLE
404 error page on ASP.NET Core

### ISSUE THREAD

**Issue by GoodJeans** [MicrosoftDocs/TeamBlogFeedback#55]
I'm new to development, currently I'm following the guide on the link mention below. 

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.1#comments-container

However there are many pages that has 404 error page when clicked on them. 

Although I can download the PDF file to continue the tutorial, but I am stuck as I'm not able to understand I read the comments section to solve my bugs! 

Please fix the pages that redirect to 404 error pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by cosmictinydust** [comment]
I had the same problem. need to help!

**Comment by dend** [comment]
@GoodJeans @cosmictinydust this should be resolved, thank you for the feedback!
