### ISSUE TITLE
There shouldn't a difference between product and documentation feedback. 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/TeamBlogFeedback#6]
If something doesn't work, as a user how am I supposed to know if its a bug in the product or its documentation?

Also, I'm inevitably going to put something in the "wrong" bucket and it will get closed with a "this is for the other feedback, open it there".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* [Content](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* [Content Source](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: unspecified

**Comment by mgkuhn** [comment]
I disagree. In the old system, you could *only* provide feedback on the documentation, i.e. you could only attach your feedback to a specific web page of the documentation. It was far from obvious how (and on which specific documentation page) to provide feedback about a product defect that is not related to a specific page of the documentation. Spreading product feedback across documentation web pages makes it more difficult for others interested in the same issue to quickly find the discussion thread. Keeping them separate makes it much easier to categorize product issues by subsystem and assign them to the relevant developer (who may not be in charge of any particular page of the documentation).

**Comment by StingyJack** [comment]
Perhaps part of the error is in thinking the old system was or was not only for documentation feedback. 

Docs has always been easier to find, and as I dont work at/for MSFT or have an "in", its historically about the only place I could get help outside of stackoverflow (SO has been invaluable, but its generally still outsiders like me, postulating and speculating). If I'm having a problem with the program/product, I'm going to be on the doc pages already. Finding a discussion there about the problem would be awesome. Also, the new/recent option of devcommunity is not working out so great for me either with only 54 issues out of the 223 I've opened resolved to some degree of satisfaction (one of the open ones has been in "triaged" status for 340 days).  

If you do work for on the producer side of the discussion, I can see how having the work neatly pre-organized would be appealing, but I could never ask my customers to effectively "sorry, call a different helpdesk number" when they are stuck with a problem and are already on the phone. Resentment kills any relationship, not just personal ones. 

I don't see what's to really be gained when most of the time users are just going to flip a coin most times and pick one of the two, and the producer will just have to move the issue around anyway.

**Comment by scout208** [comment]
Yeah, I have to agree with StingyJack, at least on the last point. I knew that if there was something in the documentation that should be changed, I would make a GitHub issue for it. But, if I had some question about how a feature of the product the documentation was for was supposed to work, that's when I would usually post the comment using LiveFyre. I didn't realize that the comments on the documentation pages were meant to be used for documentation feedback. For me it was usually a way to clarify what should be happening with the product. 

I can tell that having just a single, unanimous comments thread led to there being feedback on there on documentation alongside product feedback, so I agree it is good to separate them, but why move the product feedback to a different system entirely? Why not use GitHub for that too? 

I guess what I really want to know is in the future where should I go if I need help with how to use the product, or if there is an issue with the product itself, and is it easy for me to get there?

**Comment by SteveBurkettNZ** [comment]
I'm finding all the product feedback links I've seen at the bottom of docs pages are sending me to the corresponding uservoice or ideas site for the product which are intended for Product Suggestions, not Product Feedback. 

We've lost a place to often get direct clarifications on product usage/licensing/roadmaps from the product owner themselves, and to point out bugs and issues with that software.

They really needed to introduce three links to the bottom of Docs pages:

- Documentation Feedback (hosted on GitHub)
- Product Suggestions (pointing to the corresponding Microsoft UserVoice/Ideas/Experience site for the product)
- Product Feedback (hosted on GitHub)

**Comment by StingyJack** [comment]
uservoice is broken, or rather the way MSFT uses it is broken

https://developercommunity.visualstudio.com/content/problem/165853/the-vs-ide-uservoice-still-runs-out-of-votes.html

https://developercommunity.visualstudio.com/content/problem/56328/get-rid-of-uservoice.html

**Comment by mlottner** [comment]
@StingyJack Thanks for taking the time to give us your feedback. 
We've worked to improve the feedback mechanisms since your original post. 
Within Git, use the **edit** option to suggest changes to pages you feel are in error, and use the **feedback** option to ask questions to either doc or product owners. Both are answered. 
If a page doesn't have a feedback option, you can use the **Is this page helpful** vote to add your comment or feedback. 
Appreciate your contribution to our community!

**Comment by StingyJack** [comment]
@mlottner - thanks, I'm aware of how to try to fix docs pages that need it (though some page authors/page owners seem to be awol).

I'm going to have to disagree that product feedback are answered. In my experience, I'm at _least_ 5x more likely to get a "sorry, nobody from the assigned product team could look at it in after being opened for > 90 days" closure than to get a response from a product owner or product team member. Last time i tallied up my reported feedback, only about 1 out of 20 problems I had reported was handled satisfactorily.

That aside, I still see two buttons on every page, and this is the crux of my complaint. Users should have a single place to request information or assistance from Microsoft. How you triage and route that request and respond/resolve it is up to you.

The multiple week lag of docs behind the product delivery is a great example of the wasted effort created by this two button system. Product not working the same as the day before and this is causing some production issue. Support Engineer consults docs, docs don't reflect this change. What button should one click?

I pick docs first given the success rate with product feedback. 3 days later the item is closed with a note saying "it looks like you are having a product problem, kindly go ask them". Usually at that point I have to argue with or remind whomever closed the issue that the docs page still doesn't match the current reality. Sometimes this takes multiple exchanges. All this is wasted time when there could be a streamlined experience with a single point of entry for users.

> We've worked to improve the feedback mechanisms since your original post.

I don't see that. I still have the same problems with this system. Nothing has been materially changed in that, so I don't feel that this being closed is legit.

**Comment by mlottner** [comment]
@StingyJack Thanks for your fast response. 
While I can't speak for every content developer, product or every product owner, we all do our best to answer and respond to customer issues as fast as we can. 
While I can appreciate your desire for a single point of contact, and have flagged your suggestion to the relevant infrastructure related parties, leaving this specific blog feedback issue open (or re-opening) will not change the current structure. I can attest that your feedback on this feature has been noted and recorded and flagged to all relevant parties.

Again, we do appreciate your contribution to our community and suggestions for feedback improvement.

**Comment by mgkuhn** [comment]
@Stingray I think you may be going down a dangerous path here when you try to conflate product assistance with feedback. A feedback channel is aimed at expert users who have found a bug or want an efficient way to communicate a product-improvement suggestion directly to developers. Product assistance is for less experienced users who are struggling with understanding the product and require some hand holding from documentation and help desk staff. If you encourage a software company to lump both together, then you will invariable end up everything being routed to the product-assistance folks, and as a result you cut off a valuable route for experienced users to provide direct feedback to developers. The problem is that there are always two orders of magnitude more people seeking product assistance than being able to provide actionable technical high-quality product feedback. Therefore software companies will always want to protect the productivity of their developers by shielding them from product-assistance tasks.

I think Microsoft has done the right thing here already by learning from Github's open-source community of how to provide an easy feedback mechanism for experienced developers, and you might well end up killing that if you confuse it with a customer support function, which is something with very different requirements. Github issues are brilliant for getting expert users in touch with developers, but they are absolutely not the right tool for the far more repetitive task of regular end-user support.

**Comment by StingyJack** [comment]
@mgkuhn - you mean me?

**Comment by StingyJack** [comment]
@mlottner - can I get your opinion on things like this https://github.com/MicrosoftDocs/vsts-docs/issues/5375

This was just the first one I happened to come across that wasn't my own issue. The closer on it has done the same to me several times, and all but one or two were done incorrectly. The closer relented only after getting a response in kind, and then only to pacify/defuse.

If you really think the system is right, and you value the customer experience, I think that it would be wise to review anything closed by a canned first response message. Those sharp responses are actually examples of the damages the two-option system brings with it.

**Comment by mlottner** [comment]
@StingyJack I fully appreciate your passion about this feedback issue. Thanks you for continuing the conversation. 
While I can't speak to how every person responds to GitIssues, I can tell you that our singular goal is the be helpful. Your feedback allows us to understand your perspective, fix issues when they are raised and offer you (and the thousands of other users that "talk" to us via multiple feedback channels) on a continual basis, the very best service and support that we can. 
We want you to be as successful as possible using our products. 
However, we are human and we do make mistakes. That is the perhaps the "cost" in any feedback workflow when not talking to a bot.
I will raise the issues you've mentioned here to a larger forum, and again, we sincerely appreciate your taking the time to share both your concerns and suggestions.
