### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by darting** [MicrosoftDocs/TeamBlogFeedback#61]
Hi there, just wondering if it is (or it will be) an open source project for `docs.microsoft.com`. thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079073a-0dd9-3b9b-c160-76e0dd525a3c
* Version Independent ID: 631788a5-f4bc-7df0-0540-2a0f67b631de
* Content: [Introducing docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/introducing-docs-microsoft-com)
* Content Source: [teamblog/introducing-docs-microsoft-com.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-docs-microsoft-com.md)
* Service: **unspecified**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by jmcjohnjohn** [comment]
feed back on

**Comment by dend** [comment]
Hello! Currently there are no plans to do this. Please check out [DocFX](https://dotnet.github.io/docfx/) if you would like to try the tool that powers our site!
