### ISSUE TITLE
Download PDF

### ISSUE THREAD

**Issue by KalmanShlomo** [MicrosoftDocs/TeamBlogFeedback#65]
Today, May 9, 2018, I clicked on Download PDF and the PDF only reflects updates on or prior to Feb. 24, 2018. Can the PDF be updated to include the latest updates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
@KalmanShlomo can you comment on what PDF you are referring to?

@dastaffo - assigning to you to follow-up.

**Comment by KalmanShlomo** [comment]
There is a link in the bottom left corner of the screen. See bottom of attached screenshot.

When this link is clicked, a new window opens with the PDF (it takes time to load). This PDF does not reflect the most current updates as indicated by the date (beside "minutes to read").
![docs screenshot](https://user-images.githubusercontent.com/39132511/39846796-9fc463d4-53cb-11e8-9f2a-f5f53cd843db.PNG)

**Comment by KalmanShlomo** [comment]
Sorry, I mistakenly closed this issue. I did not mean to do so.

**Comment by dend** [comment]
@dastaffo can you follow-up here, please?

**Comment by dastaffo** [comment]
@adkinn Can you help investigate?

**Comment by dastaffo** [comment]
@KalmanShlomo As part of the update to the Power BI documentation, it now should have the latest PDF information
