### ISSUE TITLE
Commenting on docs.microsoft.com

### ISSUE THREAD

**Issue by Claus-Andersen** [MicrosoftDocs/TeamBlogFeedback#67]
We are now more than 3 months down the road from the original post around the new comment "system"., and it still in a limbo state. I think we all understand the you guys from MS is working on it AND that there are some reasons that it's not yet ready, but please act and open up for comments on docs again until the new functionality is available!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by mlottner** [comment]
@Claus-Andersen Thanks for taking the time to leave us blog feedback. 
The commenting is now fixed and working. Appreciate your patience as we got through the growing pains of moving systems. 
I'm closing this issue, but feel free to re-open if/as needed with blog feedback
