### ISSUE TITLE
Amazing New Partnership for Our Future

### ISSUE THREAD

**Issue by envagy37** [MicrosoftDocs/TeamBlogFeedback#72]
This has been by far the very best news I've heard so far and it will be much better for all of us, as we will all benifit greatly in softwear design, compatability issues, and we can all contribute in it to end up with super products we all dreamt about having it with Microsoft,... Thank you Mr. Gates

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-gb/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
Thanks for the feedback!
