### ISSUE TITLE
Try It For Web API Projects

### ISSUE THREAD

**Issue by AlexHedley** [MicrosoftDocs/TeamBlogFeedback#73]
Is this something you’d bring to the Help Pages for our own APIs?

Creating Help Pages for ASP.NET Web API
https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/creating-api-help-pages

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8833410e-2016-3687-4ff0-296652bb6d87
* Version Independent ID: f6a120df-bfab-a876-2c0d-a84e8710f7ef
* Content: [Announcing Updates to the REST API Experience](https://docs.microsoft.com/en-gb/teamblog/announcing-rest-improvements?WT.mc_id=docsmsft-twitter)
* Content Source: [teamblog/announcing-rest-improvements.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/announcing-rest-improvements.md)
* Service: **unspecified**
* Product: **team-blog**
* GitHub Login: @hellosnow
* Microsoft Alias: **jehuan**

**Comment by AlexHedley** [comment]
Useful doc links on [118](https://github.com/MicrosoftDocs/TeamBlogFeedback/issues/118)

**Comment by mlottner** [comment]
@AlexHedley Thanks for leaving us blog feedback. 
I'm closing this issue as resolved, but feel free to re-open if/as needed to leave additional blog feedback.

**Comment by AlexHedley** [comment]
@mlottner what is the resolution? Has this new functionality been implemented as an option in the WebApi Help project?

**Comment by mlottner** [comment]
@AlexHedley Sorry, perhaps I didn't understand your original feedback. 
You wrote: "Is this something you’d bring to the Help Pages for our own APIs?"
I've re-assigned this issue to the owner of that docs page. Can you explain your request or feedback again to make sure we've understood.

**Comment by AlexHedley** [comment]
Hi @mlottner the blog article is explaining the new feature of the "REST API browser" with the new "Try It" button.

Currently there is a Project type you can add to your own custom .NET API Projects that add the REST help pages (link above) but there isn't an option to "Try It", I was wondering if this new functionality would be added to the above "Help" pages?

**Comment by AlexHedley** [comment]
Much like [Adding a simple Test Client to ASP.NET Web API Help Page](https://blogs.msdn.microsoft.com/yaohuang1/2012/12/02/adding-a-simple-test-client-to-asp-net-web-api-help-page/) but officially.

**Comment by mlottner** [comment]
@AlexHedley I don't know of any plans, but I tagged the page owner so let's wait for their response.

**Comment by scottaddie** [comment]
@AlexHedley The blog post describes a feature intended for use ONLY in our docs.microsoft.com platform. If you want something similar for your ASP.NET 4.x Web API, install the third-party [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle) package. After installing, you'll have access to a page similar to the following:

![image](https://user-images.githubusercontent.com/10702007/69579631-82ac5880-0f98-11ea-84a3-da952c88d9c8.png)

**Comment by AlexHedley** [comment]
Hi @scottaddie thanks for the reply, I currently use Swagger via Swashbuckle, it’s great and works really well.

Do you know if this MS version is something you’d look to add as a feature to the Help project, seems like a really useful tool that developers would love to add to their own projects

**Comment by scottaddie** [comment]
@AlexHedley I'm not aware of any plans to do so. The majority of the team's efforts are focused on ASP.NET Core at this time.

A Microsoft-authored testing tool that might interest you is the [HTTP REPL](https://docs.microsoft.com/aspnet/core/web-api/http-repl?view=aspnetcore-3.0&tabs=windows). You'll need the .NET Core SDK to install it; however, it can be used to test ASP.NET 4.x Web APIs from the command line. This tool essentially does the same thing as a "Try It" button.

**Comment by AlexHedley** [comment]
Thanks, another great tool I’ve used, works well locally. Guess I’ll stick with Swashbuckle atm, appreciate you taking the time to reply and sharing some options :-)

**Comment by scottaddie** [comment]
@mlottner You can close this issue now.
