### ISSUE TITLE
Location Header missing in POST HTTP response

### ISSUE THREAD

**Issue by adeenadayalan** [MicrosoftDocs/TeamBlogFeedback#74]
I have a Logic App which calls the HTTP Post call for a refresh(https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-async-refresh#post-refreshes). I get a HTTP OK response and the refresh is initiated. However, I do not find the Location Header field in the response. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by mlottner** [comment]
@adeenadayalan Thanks for leaving us site feedback. 
Make sure to leave page feedback on the specific docs page of your inquiry or issue to ensure the content/product owner can respond quickly. 
I'm closing this issue for now, but feel free to re-open it with site feedback if/as needed.
