### ISSUE TITLE
has potential, but GitHub is better

### ISSUE THREAD

**Issue by ImageQC** [MicrosoftDocs/TeamBlogFeedback#75]
Making a post on the new MS product feedback isn't a great experience. The form is too small and I can't find details of previous posts. You should keep GitHub until you can deliver something better

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-gb/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by ImageQC** [comment]
I'm referring to https://feedback.azure.com/forums/355860-azure-functions/filters/my_feedback. This seems to be the replacement for posting directly to GitHub. 

Other points:

https://feedback.azure.com/forums gives 404 error rather than taking you to a list of the forums, as one might expect. 

The sign-on is often difficult due to the automagical way Microsoft decides which account I am using - mostly it gets it wrong so I need to logoff, login, etc. It would be much better for MS to accept that people have a number of different accounts (work, home, academic, etc) and therefore present them with a list and ask for selection. Ok, it adds a single click, but better than what happens most of the time now. MS could add an item in account settings - default account or present list of accounts.

**Comment by LukasGibb** [comment]
I agree totally with the comments about signing in to Microsoft services. I am in the same boat, old hotmail account (which is my XBox live user and now my login for Windows 10 on my home PC), then I have several accounts through work that I log in with (MSDN Subscriber account, individual VSTS login etc). Microsoft will get it wrong 80% of the time and require that I log off and back on to access the services with the correct account. Very frustrating at times. I have similar problems with YouTube and some other services though so I understand it's a complex problem to solve.

**Comment by mlottner** [comment]
@ImageQC @LukasGibb Thanks for taking the time to give us your feedback. 
I've forwarded your comments about your frustrations with site experience and logins with multiple aliases. 
Closing this thread, but feel free to re-open if/as needed.
