### ISSUE TITLE
Replication of this platform

### ISSUE THREAD

**Issue by clayhagler** [MicrosoftDocs/TeamBlogFeedback#76]
This model is great. How does one replicate what you have done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079073a-0dd9-3b9b-c160-76e0dd525a3c
* Version Independent ID: 631788a5-f4bc-7df0-0540-2a0f67b631de
* Content: [Introducing docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/introducing-docs-microsoft-com)
* Content Source: [teamblog/introducing-docs-microsoft-com.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/introducing-docs-microsoft-com.md)
* Service: **unspecified**
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by TomasDeceuninck** [comment]
I too would like some more feedback on the technical implementation of the docs.microsoft website.

**Comment by piyushpaliwal** [comment]
They are using [DocFX](https://dotnet.github.io/docfx/) as the underlying platform.

**Comment by dend** [comment]
What @piyushpaliwal said is correct - we use DocFX with a set of extensions on top of it to render content.

**Comment by DMiradakis** [comment]
@dend Would you mind sharing a list of the specific extensions you use on top of DocFX? Thanks!
