### ISSUE TITLE
Small typo Israel

### ISSUE THREAD

**Issue by aribornstein** [MicrosoftDocs/TeamBlogFeedback#77]
Great post small comment Israel in the line "Cloud Developer Advocate / Isreal" is misspelled. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94615642-7eb7-83dd-52f1-ef6b78c687cf
* Version Independent ID: 69e13745-a61d-9309-96b8-c102d01a70ec
* Content: [Join our team and make the world better for developers!](https://docs.microsoft.com/en-us/teamblog/awesome-jobs?WT.mc_id=jobs-twitter-jeffsand)
* Content Source: [teamblog/awesome-jobs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/awesome-jobs.md)
* Service: **unspecified**
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by dend** [comment]
Good catch, this is now fixed!
