### ISSUE TITLE
Some links in Awesome Jobs are broken

### ISSUE THREAD

**Issue by LuceCarter** [MicrosoftDocs/TeamBlogFeedback#79]
There are currently 4 Senior Content Developer roles listed but only 1 works. The first 2 point to expired role adverts and the final one links to the main careers website.

Sorry if a PR can be done on this, searching 805 repo's on a mobile phone is hard.

**Comment by dend** [comment]
@marywill99 can you please help check this?

**Comment by LuceCarter** [comment]
This issue still exists with links in the Content Developer section.
The bottom links still leads to the careers website.

**Comment by dend** [comment]
This has now be addressed! Thanks for the feedback!
