### ISSUE TITLE
More language support

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/TeamBlogFeedback#8]
Please support Vietnamese documents

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com | Microsoft Docs](https://docs.microsoft.com/vi-vn/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by mlottner** [comment]
@nguyenthanhliemfc Thanks for taking the time to give us your feedback. 
I've flagged this request to our language specialists for awareness and consideration. 

Appreciate your contribution to our community!

I'm closing this issue, but feel free to re-open if/as needed.
