### ISSUE TITLE
Is appendBlob method for video File supported?

### ISSUE THREAD

**Issue by komalpharate** [MicrosoftDocs/TeamBlogFeedback#80]
Hi,
I tried appendBlob method.
Now, I want to use appendBlob method to append video files.
Is it possible?
And how?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-gb/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Service: **unspecified**
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
Hi @komalpharate - what is this feedback in relation to?

**Comment by komalpharate** [comment]
Hi,
This feedback is for Microsoft Azure blob implementation steps.
https://docs.microsoft.com/en-us/rest/api/storageservices/append-block

**Comment by smrifat** [comment]
Thanks for this link
<a href='https://www.clippingpathquick.com/' title='Clipping Path Service'>clipping path service</a>

**Comment by mlottner** [comment]
@komalpharate Thanks for your blog feedback. 
I've reassigned this question to the page owner of the [page you referenced](https://docs.microsoft.com/en-us/rest/api/storageservices/append-block). 
In the future, make sure to open feedback or questions on the specific docs page to ensure your query gets the fastest response possible.
Appreciate your patience.

**Comment by tamram** [comment]
@komalpharate - It would be better to use a block blob for video files, as block blobs are optimized for streaming. 

Append blobs are ideal for functions such as logging, where you only need to append data to the end of the blob.

For more information, see [Understanding block blobs, append blobs, and page blobs](https://docs.microsoft.com/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs).

#please-close
