### ISSUE TITLE
Are the stickers coming back?

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/TeamBlogFeedback#85]
As a fan and spell checker of docs.microsoft.com I would love to get one of these.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1aa22f-6031-0e08-5437-c5a26b430cb8
* Version Independent ID: f6f5810a-c249-c726-444f-66569eb8b6c5
* Content: [Rewarding Our Community & Fans](https://docs.microsoft.com/en-us/teamblog/rewarding-community-fans)
* Content Source: [teamblog/rewarding-community-fans.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/rewarding-community-fans.md)
* Product: **team-blog**
* GitHub Login: @dend
* Microsoft Alias: **dendeli**

**Comment by dend** [comment]
Hello! At this time, we are not providing any additional stickers. Make sure you follow us [on Twitter](https://twitter.com/docsmsft) for any upcoming promotions.
