### ISSUE TITLE
Adding CRUD views in Details.CSHTML page

### ISSUE THREAD

**Issue by Mokolone** [MicrosoftDocs/TeamBlogFeedback#87]
The tutorial for Contoso University does not show on how one can capture changing data. For, example, a student during a semester will write two class tests, then a final exam. Class tests counts a percentage towards final grade and so is exam. How will then one write views that can be displayed in Details, page that shows a grade for first test, the second test, the final exam grade ? Also, there is no tutorials on @Render a view inside another view. The documentation is inadequate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by dend** [comment]
Hi @Mokolone - can you please share what tutorial this is related to?

**Comment by dend** [comment]
Closing as this is not related to the team blog, and not additional information was provided regarding the source of the issue.
