### ISSUE TITLE
Identity is missing in response of https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service#instance-metadata-data-categories Api call

### ISSUE THREAD

**Issue by RoshanKumarMicrosoft** [MicrosoftDocs/TeamBlogFeedback#88]
Created one azure VM and assigned identity to Vm but still not getting identity in response .

Api
 $vmdata = Invoke-RestMethod -Headers @{"Metadata"="true"} -URI http://169.254.169.254/metadata/instance?api-version=2018-02-01 -Method get

Response:- 
{
    "compute":  {
                    "location":  "SouthIndia",
                    "name":  "rokJavawindowvm",
                    "offer":  "WindowsServer",
                    "osType":  "Windows",
                    "placementGroupId":  "",
                    "platformFaultDomain":  "0",
                    "platformUpdateDomain":  "0",
                    "publisher":  "MicrosoftWindowsServer",
                    "resourceGroupName":  "RokJavaResourceGroup",
                    "sku":  "2016-Datacenter",
                    "subscriptionId":  "c94bda7a-0577-4374-9c53-0e46a9fb0f70",
                    "tags":  "",
                    "version":  "2016.127.20180510",
                    "vmId":  "598b6f38-bd23-4854-8afa-b7a01fb786af",
                    "vmScaleSetName":  "",
                    "vmSize":  "Standard_D2s_v3",
                    "zone":  ""
                },
    "network":  {
                    "interface":  [
                                      "@{ipv4=; ipv6=; macAddress=000D3AF288A5}"
                                  ]
                }
}

Identity is missing in response. Please suggest how to get Identity through metadata service .

**Comment by dend** [comment]
@iainfoulds can you please take a look at this feedback?

**Comment by iainfoulds** [comment]
@harijayms - Looks like a customer is reporting an issue with the expected output from IMDS. Can you validate that the examples in the doc are correct and up to date, please? Let me know if you help updating the docs if there are any required changes.

**Comment by rokmicrosoft** [comment]
@harijayms  @iainfoulds  We are blocked due to this ..Can you please look this into priority? Thanks.

**Comment by harijayms** [comment]
All identity queries are at a different level, see detailed documentation for that here https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/how-to-use-vm-token which is linked from the identity section in the doc

**Comment by harijayms** [comment]
@rokmicrosoft please correct the queries

**Comment by rokmicrosoft** [comment]
@harijayms https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service#retrieving-metadata-in-windows-virtual-machine 
In response it has mentioned Identity will be also there for particular API version  but it is missing in response. The link you have shared is to get access token not identity.

**Comment by harijayms** [comment]
@rokmicrosoft missing something identity is a section just like scheduled events or compute. Its a hierarchy in the call , what are you trying to get when you say you have assigned identity to the VM I am assuming that you are putting either a system assigned or user defined identity. The Metadata endpoint will give you tokens  that you can use for the identity, what specifically are you looking for?

**Comment by mlottner** [comment]
@RoshanKumarMicrosoft Thanks again for your feedback and inquiry. 
I'm closing this issue as it appears the issue was resolved for you. 
Feel free to re-open if/as you need. 
Appreciate your contribution to our community.
