### ISSUE TITLE
Can we label this January 2018 release Notes?

### ISSUE THREAD

**Issue by thedanfernandez** [MicrosoftDocs/TeamBlogFeedback#9]
## Get to work Den!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e493b93-e2f1-f396-9e87-d62dc93fbd04
* Version Independent ID: a32343b9-b3d8-32be-4a27-c57bb0a20453
* Content: [Starting 2018 With docs.microsoft.com Improvements | Microsoft Docs](https://docs.microsoft.com/en-us/teamblog/release-notes-start-2018#feedback)
* Content Source: [teamblog/release-notes-start-2018.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/release-notes-start-2018.md)
* Service: **unspecified**
* GitHub Login: @dend
* Microsoft Alias: **danielfe**

**Comment by dend** [comment]
Fixed in https://github.com/MicrosoftDocs/blog/pull/136
