### ISSUE TITLE
Error: The same apk was uploaded as app and test

### ISSUE THREAD

**Issue by usri** [MicrosoftDocs/TeamBlogFeedback#91]
I followed this guidance https://docs.microsoft.com/en-us/appcenter/quickstarts/android/test in order to make the test run.

here is the command that I am using 

`> appcenter test run espresso --app "******" --devices ***** --app-path C:\Users\******\repos\appcenter-sampleapp-android-master\app\build\outputs\apk\androidTest\debug\app-debug-androidTest.apk --test-series "master" --locale "en_US" --build-dir C:\Users*****\repos\appcenter-sampleapp-android-master\app\build\outputs\apk\androidTest\debug`

however, it gives Error: The same apk was uploaded as app and test; and when I am trying to use the released apk, it gives me Error: test apk does not include Test-Cloud Espresso extension, although, I run the below commands successfully

```
>  ./gradlew assembleDebug
> ./gradlew assembleDebugAndroidTest
> 
```

**Comment by dend** [comment]
Hello! Please open the issue within the documentation page (there is a link at the bottom) - the feedback in this repository is related to the team blog.
