### ISSUE TITLE
Some "apply today" links lead to empty list on career site

### ISSUE THREAD

**Issue by brunolewin-msft** [MicrosoftDocs/TeamBlogFeedback#92]
Some links (example below for PM Jobs) contain different keyword than the job describtion. Notice the missing final "s":
https://careers.microsoft.com/us/en/search-results?keywords=%23apexawesomejob 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94615642-7eb7-83dd-52f1-ef6b78c687cf
* Version Independent ID: 69e13745-a61d-9309-96b8-c102d01a70ec
* Content: [Join our team and make the world better for developers!](https://docs.microsoft.com/en-us/teamblog/awesome-jobs)
* Content Source: [teamblog/awesome-jobs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/awesome-jobs.md)
* Product: **team-blog**
* GitHub Login: @jeffsand
* Microsoft Alias: **jeffsand**

**Comment by dend** [comment]
Thanks! This should now be addressed.
