### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by EdZava** [MicrosoftDocs/TeamBlogFeedback#95]
And how can I export to PDF for example with the same display of the Docs Preview extension?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 950150af-0c7e-d146-53fc-0af72ab7c70a
* Version Independent ID: 5d792ab0-26c7-90b6-fa3f-c9d32e78c18a
* Content: [A New Release of Docs Authoring Pack for VS Code](https://docs.microsoft.com/en-us/teamblog/docs-extension-update)
* Content Source: [teamblog/docs-extension-update.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/docs-extension-update.md)
* Product: **team-blog**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by dend** [comment]
Hello! Currently the extension does not facilitate PDF export - you can take a look at the Visual Studio Marketplace for any other PDF extensions.
