### ISSUE TITLE
Keep old comments

### ISSUE THREAD

**Issue by auberginekenobi** [MicrosoftDocs/TeamBlogFeedback#97]
This is a great move, but concerned that the loss of old comments would represent a considerable loss of accumulated information by the community.  MS needs to find a way to transition old comments into the new system so that docs users can leverage past users' issues and fixes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by petemoore** [comment]
I couldn't agree more!

**Comment by dend** [comment]
Hi folks, we are working on ensuring that old comments are archived. Rest assured that this is work in progress.

**Comment by ajayyy** [comment]
It's been months, are you sure it is actually going to happen?
