### ISSUE TITLE
Excel Workbook Download?

### ISSUE THREAD

**Issue by phoneticus** [MicrosoftDocs/TeamBlogFeedback#99]
I like the article and the charting examples.  Is there a place where we can download the Excel workbook with sample data and the charts?  This would make it so much easier to work with the examples.  Thank you so much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0193ed76-3eec-18ac-512f-45f8118dde34
* Version Independent ID: 8e693833-3e45-2bb8-ddc2-d0c54936c3c1
* Content: [A New Feedback System Is Coming to docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/a-new-feedback-system-is-coming-to-docs)
* Content Source: [teamblog/a-new-feedback-system-is-coming-to-docs.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/a-new-feedback-system-is-coming-to-docs.md)
* Product: **team-blog**
* GitHub Login: @EisenbergEffect
* Microsoft Alias: **EisenbergEffect**

**Comment by mlottner** [comment]
@phoneticus Thanks for taking the time to give us your feedback.
I'm closing this issue as the page you left feedback for doesn't have an Excel workbook or examples available for download. 
If you need further assistance, please re-open and let us know how we can help!
